/**
 * Issue 1089 — the persistence seam must be INVISIBLE.
 *
 * `RecipeManager` and `CraftingSystemManager` now reach `game.settings` through a
 * `CraftingDefinitionRepository` instead of calling `setSetting` themselves. That is
 * a decoupling with no intended behaviour change, so the acceptance bar is the
 * absence of change — and the existing suites cannot show it, because they assert on
 * the in-memory managers rather than on the bytes that reach storage.
 *
 * `tests/fixtures/craftingDefinitionWriteLog.golden.json` was generated by running
 * the scenario below against the base commit, BEFORE the repository existed. This
 * suite reruns the same scenario through the seam and requires:
 *
 *   1. the same number of writes,
 *   2. in the same order, against the same setting keys,
 *   3. each write byte-identical (SHA-256 over the serialized value), and
 *   4. the same final persisted corpus.
 *
 * Points 1 and 2 are what a repository seam is most likely to break — a per-record
 * `put` that flushes twice, or that flushes at a different point in a cascade, still
 * leaves a correct final corpus while doubling the write amplification this whole
 * programme exists to reduce.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

import {
  runCraftingDefinitionWriteScenario,
  summarizeScenarioRun,
} from './helpers/craftingDefinitionWriteScenario.js';

const golden = JSON.parse(
  readFileSync(
    new URL('./fixtures/craftingDefinitionWriteLog.golden.json', import.meta.url),
    'utf8'
  )
);

const { RecipeManager } = await import('../src/systems/RecipeManager.js');
const { CraftingSystemManager } = await import('../src/systems/CraftingSystemManager.js');

describe('crafting definition persistence equivalence (issue 1089)', () => {
  it('reproduces the pre-seam write log byte for byte', async () => {
    const actual = summarizeScenarioRun(
      await runCraftingDefinitionWriteScenario({ RecipeManager, CraftingSystemManager })
    );

    assert.deepEqual(
      actual.steps,
      golden.steps,
      'the scenario itself drifted; regenerate the golden deliberately rather than editing it to match'
    );

    assert.equal(
      actual.writeCount,
      golden.writeCount,
      `the seam changed how many persistence writes the scenario issues (${golden.writeCount} before, ${actual.writeCount} now). A repository that flushes per record inside a cascade looks correct in the final corpus and is still a regression.`
    );

    assert.deepEqual(
      actual.writes.map((write) => `${write.index}:${write.key}`),
      golden.writes.map((write) => `${write.index}:${write.key}`),
      'the seam changed which setting each write targets, or the order they are issued in'
    );

    for (const [index, expected] of golden.writes.entries()) {
      const observed = actual.writes[index];
      // The final corpus is compared in full below, so a digest mismatch here is
      // reported with the step that produced it — the diagnosable half of the check.
      assert.equal(
        observed.sha256,
        expected.sha256,
        `write ${index} to "${expected.key}" is not byte-identical to the pre-seam write (${expected.bytes} bytes before, ${observed.bytes} now). Every normalizer in CraftingSystemManager is a whitelist rebuild, so a key it stops emitting is dropped from storage on the next save.`
      );
    }

    assert.deepEqual(
      actual.finalCorpus,
      golden.finalCorpus,
      'the persisted corpus after the scenario differs from the pre-seam corpus'
    );
  });
});
