/**
 * Every fixture identifier a case names must exist in the lab world.
 *
 * `tests/view-lab-cases.test.js` checks that a selector's HOOKS exist in `src/` — the class names
 * and attribute names — and it deliberately strips attribute VALUES before doing so, because those
 * values are fixture ids and live here rather than in `src/`. Nothing then checked them there. That
 * left the registry's largest hand-maintained mirror unguarded: roughly fifty component, recipe,
 * tool, task, event, environment and actor ids, plus every `query.system`.
 *
 * A renamed fixture id is caught today only by a capture run — which needs harvested Foundry chrome,
 * so it does not run on a fork PR, does not run without credentials, and is not part of `npm test`.
 * Between the rename and the next successful capture, the case silently cannot reach its state.
 *
 * The check is exact-value, not substring: `sm-longsword` must BE an id in the world, not merely
 * appear somewhere in the file. Substring matching is how the sibling guard in `view-lab-cases`
 * passed over six broken selectors before it was tightened.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { VIEW_LAB_CASES } from '../scripts/lib/viewLabCases.js';
import { buildLabContent, LAB_SYSTEM_IDS } from './view-lab/world/labContent.js';
import { buildLabActors, buildDocumentIndex } from './view-lab/world/labActors.js';
import {
  LAB_JOURNAL_CASE_STATE_RUN_IDS,
  buildLabRunStates,
  createLabJournalCaseController,
  installLabRunStates,
} from './view-lab/world/labRunStates.js';
import { Recipe } from '../src/models/Recipe.js';
import { RecipeVisibilityService } from '../src/systems/RecipeVisibilityService.js';
import { CraftingRunManager } from '../src/systems/CraftingRunManager.js';
import { SalvageRunManager } from '../src/systems/SalvageRunManager.js';
import { GatheringRunManager } from '../src/systems/GatheringRunManager.js';
import { installFoundryShim } from './view-lab/foundry/installFoundryShim.js';

const content = buildLabContent();
const actors = buildLabActors(content);
installFoundryShim({
  documents: buildDocumentIndex(content, actors), content, actorList: actors,
  scenes: [], settings: new Map(), i18n: { localize: (key) => key }, seed: {},
});

/** @returns {string[]} Run identities actually generated by the default and focused fixtures. */
function labRunIds() {
  return [null, ...Object.keys(LAB_JOURNAL_CASE_STATE_RUN_IDS)].flatMap((state) =>
    Object.values(journalFixture(state).containers).flatMap((container) =>
      [...Object.values(container.active), ...container.history].map((run) => run.id)
    )
  );
}

/**
 * Every modifier-library entry id the lab world declares.
 *
 * READ FROM THE AUTHORED SHAPE, not from `system.modifiers`. The fixture authors the library
 * where the pre-`1.23.0` world carried it — `craftingCheck.checkModifiers` — and the lab boot
 * runs every migration over it, so the key the DOM is eventually built from does not exist in
 * `buildLabContent()` at all. Deriving from `system.modifiers` produced an EMPTY set, which
 * then rejected every id a case legitimately names.
 *
 * @returns {string[]}
 */
function modifierLibraryIds() {
  return content.systems.flatMap((system) =>
    [
      ...(system.modifiers ?? []),
      ...(system.checkModifiers ?? []),
      ...(system.craftingCheck?.checkModifiers ?? []),
    ].map((entry) => entry.id)
  );
}

/** Attribute name -> the set of values the lab world actually contains. */
const IDENTITY_SOURCES = {
  'data-component-id': new Set(content.components.map((entry) => entry.id)),
  'data-recipe-id': new Set(content.recipes.map((entry) => entry.id)),
  'data-manager-tool-id': new Set(content.tools.map((entry) => entry.id)),
  'data-gathering-task-id': new Set(content.gatheringConfig.tasks.map((entry) => entry.id)),
  'data-task-id': new Set(content.gatheringConfig.tasks.map((entry) => entry.id)),
  'data-gathering-event-id': new Set(content.gatheringConfig.events.map((entry) => entry.id)),
  'data-environment-id': new Set(content.environments.map((entry) => entry.id)),
  'data-knowledge-actor': new Set(actors.map((entry) => entry.id)),

  // The ten below were the gap this file's own header describes and did not actually close. Each
  // pins a fixture id in a selector, so a rename is caught only by a capture run — which does not
  // run on fork PRs, and which is the slowest possible place to learn about a typo.
  'data-recipe-edit': new Set(content.recipes.map((entry) => entry.id)),
  'data-component-select': new Set(content.components.map((entry) => entry.id)),
  // The recipe browser's bulk selection control (issue 1010) — the exact mirror of
  // `data-component-select` above, and unguarded until now: the three
  // `manager-recipes-bulk-edit*` cases pin fixture ids in their row clicks, so a rename
  // would otherwise surface only in a capture run.
  'data-recipe-select': new Set(content.recipes.map((entry) => entry.id)),
  'data-system-id': new Set(content.systems.map((entry) => entry.id)),
  // The system Modifiers card's per-entry row and its roll note (issue 1118). Both pin a
  // library entry id, and `manager-system-edit-modifier-rolls` opens one by id in its steps and
  // asserts the note by id in its `expectSelector` — so a renamed entry would break the case in
  // two places and be caught by neither until a capture run.
  'data-world-modifier': new Set(modifierLibraryIds()),
  'data-world-modifier-roll-note': new Set(modifierLibraryIds()),
  // The essence browser's bulk selection control (issue 1036) — the exact mirror of
  // `data-component-select` and `data-recipe-select` above. The essence bulk-edit case pins
  // fixture ids in its row ticks, so a rename would otherwise surface only in a capture run.
  // Derived from the SYSTEM's declared vocabulary for the same reason `data-essence-id` is:
  // deriving it from the essences components happen to carry would falsely reject a
  // declared-but-uncarried essence.
  'data-essence-select': new Set(
    content.systems.flatMap((system) =>
      (system.essenceDefinitions ?? []).map((essence) => essence.id)
    )
  ),
  // From the SYSTEM's declared vocabulary, which is what `adminStore` builds the browser's rows
  // from and therefore what `EssenceBrowserView` writes into the attribute. Deriving these from the
  // essences components happen to carry passes today only because the two coincide: it would
  // falsely reject a declared-but-uncarried essence (the fixture authors exactly that deliberately
  // for the `runic` TAG) and falsely accept an essence key typo'd onto a component.
  'data-essence-id': new Set(
    content.systems.flatMap((system) =>
      (system.essenceDefinitions ?? []).map((essence) => essence.id)
    )
  ),
  // Also system-declared. `content.recipeItems` is the herbalism list alone, so smithing's
  // inline `sm-book` was missing from the set and a case naming it would have been rejected.
  'data-books-scrolls-edit': new Set(
    content.systems.flatMap((system) =>
      (system.recipeItemDefinitions ?? []).map((entry) => entry.id)
    )
  ),
  // Generated ids include paginated siblings and the blind run's shared constant.
  'data-history-run-id': new Set(labRunIds()),
  // The ACTIVE-run counterpart, carried by `RunCard`. Unguarded until issue 901's blind Journal
  // cases needed it, which is the same gap `labRunIds` above describes from the other end.
  'data-run-id': new Set(labRunIds()),
  // Composite keys. The listing builds these itself, so the guard has to build them the same way
  // or it would reject the very values the DOM carries.
  'data-inventory-card': new Set(
    content.systems.flatMap((system) =>
      (system.components ?? []).map((component) => `${system.id}:${component.id}`)
    )
  ),
  // The carrier's key is `item.uuid || item.id`, and an owned item's uuid is the component's
  // `originItemUuid` — which `component()` DEFAULTS to `Item.<id>` but two components override to
  // a shared uuid. Rebuilding the default instead of reading the field admitted a value the DOM
  // never carries and rejected the one it does.
  'data-essence-carrier': new Set(
    content.components.map((entry) => entry.originItemUuid ?? `Item.${entry.id}`)
  ),
};

/** Every `key="value"` pair in a selector, in source order. */
function attributePairs(selector) {
  return [...selector.matchAll(/\[([a-z][\w-]*)\s*=\s*"([^"]*)"\]/g)].map((match) => ({
    name: match[1],
    value: match[2],
  }));
}

/**
 * The identifier pins in a selector that `IDENTITY_SOURCES` recognises, each marked with whether
 * its value exists in the lab world.
 *
 * A pin whose attribute name `IDENTITY_SOURCES` does not recognise, or whose value is empty, is not
 * returned at all — the caller never sees it, exactly as the original step loop silently skipped it.
 * Both the step sweep and the `expectSelector` sweep below call this so their extraction and
 * matching cannot drift apart.
 *
 * @param {string} selector
 * @returns {{name: string, value: string, known: boolean}[]}
 */
function identifierPins(selector) {
  const pins = [];
  for (const { name, value } of attributePairs(selector)) {
    const source = IDENTITY_SOURCES[name];
    if (!source || value === '') continue;
    pins.push({ name, value, known: source.has(value) });
  }
  return pins;
}

// `data-popover-option` is deliberately absent from IDENTITY_SOURCES, and the widening it was
// left out FOR has since happened. The attribute has one producer, `SearchablePopover.svelte`,
// which stamps it for any option carrying a `dataId`; when this note was written one caller
// supplied one — `RecipeBulkEditPanel.svelte`, with `dataId: book.id` — so its whole value space
// was recipe book ids, and the component's own contract already named the Travel tab's pickers as
// the intended adopters: an option needs an identity handle because "without one the only handle is
// the display label, which is localized and therefore not a selector".
//
// Issue 1504 widened it much further than that. `Select` stamps EVERY row, so the attribute now
// carries page sizes, recipe categories, scoped-list sort keys and check-tier ids
// beside the book ids — none of them a lab-world record, several not identifiers at all.
// A source set defined from recipe book ids would by now falsely reject eleven legitimate steps
// across ten cases, which is exactly what the absence is here to prevent (issue #1021).
//
// Twenty of the twenty-five `expectSelector`-bearing cases key on an attribute IDENTITY_SOURCES does
// not recognise — `data-bulk-book-state`, `data-essence-view`, `data-inventory-bulk-panel`,
// `data-inventory-bulk-queue-row`, and others — and fall through `identifierPins`'s skip for the
// same reason a step naming one of those attributes would. Widening IDENTITY_SOURCES to cover them
// is out of scope here (issue #1021); this sweep only guards the five that already resolve.

test('every query.system names a real lab crafting system', () => {
  const known = new Set(Object.values(LAB_SYSTEM_IDS));
  const unknown = [];
  for (const viewCase of VIEW_LAB_CASES) {
    const system = viewCase.query?.system;
    if (system && !known.has(system)) unknown.push(`${viewCase.id}: ${system}`);
  }
  assert.deepEqual(
    unknown,
    [],
    'these cases open on a crafting system the lab world does not define, so the manager falls back ' +
      'to whichever system it had and the case photographs the wrong one:\n  ' +
      unknown.join('\n  ')
  );
});

test('every fixture id a selector names exists in the lab world', () => {
  const unknown = [];
  for (const viewCase of VIEW_LAB_CASES) {
    for (const step of viewCase.steps ?? []) {
      if (typeof step !== 'object') continue;
      for (const pin of identifierPins(step.selector)) {
        if (!pin.known) unknown.push(`${viewCase.id}: [${pin.name}="${pin.value}"]`);
      }
    }
  }
  assert.deepEqual(
    unknown,
    [],
    'these selectors name a fixture the lab world does not contain, so the step matches nothing and ' +
      'the case cannot reach its state. Either the fixture was renamed or the case was:\n  ' +
      unknown.join('\n  ')
  );
});

test('every fixture id an expectSelector names exists in the lab world', () => {
  const unknown = [];
  let recognized = 0;
  for (const viewCase of VIEW_LAB_CASES) {
    if (typeof viewCase.expectSelector !== 'string') continue;
    for (const pin of identifierPins(viewCase.expectSelector)) {
      recognized++;
      if (!pin.known) unknown.push(`${viewCase.id}: [${pin.name}="${pin.value}"]`);
    }
  }

  // This sweep is prospective: today every recognised expectSelector pin duplicates a value its own
  // case's steps already pinned, so a rename is caught by the step sweep first. A guard that
  // currently catches nothing needs a guard of its own, because one wired to the wrong field or run
  // over an always-empty collection passes exactly as loudly as a correct one. Counting the pins
  // the loop above actually visited, rather than recomputing them here, is what makes that visible.
  assert.ok(
    recognized > 0,
    'this sweep visited no expectSelector pin IDENTITY_SOURCES recognises, so the assertion below ' +
      'would pass even if every case were pinned to a nonexistent fixture'
  );

  assert.deepEqual(
    unknown,
    [],
    "these expectSelectors (not steps) name a fixture the lab world does not contain, so the case's " +
      'own state assertion matches nothing even after the case reaches it. Either the fixture was ' +
      'renamed or the expectSelector was:\n  ' +
      unknown.join('\n  ')
  );
});

test('the identity sources are populated, so the checks above are not vacuous', () => {
  // A builder that returned nothing would make every assertion above pass by matching an empty set
  // against an empty set — the shape of failure this whole file exists to catch, turned on itself.
  for (const [name, values] of Object.entries(IDENTITY_SOURCES)) {
    assert.ok(values.size > 0, `no lab fixture supplies values for ${name}`);
  }
  assert.ok(Object.values(LAB_SYSTEM_IDS).length >= 5, 'expected one system per resolution mode');
});

/**
 * The lab world Item roster reaches `game.items`, which is the collection the product reads.
 *
 * `buildDocumentIndex` has always minted an Item per component, tool and recipe item, but the
 * shim built `game.items` as an EMPTY collection and only appended what a frame created at
 * runtime. `getWorldItemOptions` in `SvelteCraftingSystemManagerApp.svelte.js` maps that
 * collection directly, so every screen resolving a linked game-world Item was photographed
 * against a roster no GM has.
 *
 * It was invisible in both directions. `toolSourceSnapshot` falls back
 * `worldItem || managedItem || tool`, so a linked tile drew the TOOL's own name and art and
 * looked entirely correct while never exercising the resolved-Item path. And `sourceMissing`
 * requires a NON-EMPTY roster by design — a roster that has not loaded must not read as a broken
 * link — so `ItemDropZone`'s `missing` face could not render in the lab at all, and the case
 * written for it failed the whole capture rather than one frame.
 *
 * This asserts the wiring, not a count: a non-empty roster, every entry an Item, and a uuid the
 * index does not mint answering nothing. The third is what the `missing` face depends on.
 */
test('the lab seeds game.items from the document index, Items only', async () => {
  const { installFoundryShim } = await import('./view-lab/foundry/installFoundryShim.js');
  const documents = buildDocumentIndex(content, actors);
  installFoundryShim({
    documents,
    content,
    actorList: actors,
    scenes: [],
    settings: new Map(),
    i18n: { localize: (key) => key },
    seed: {},
  });
  const roster = globalThis.game.items.contents;
  assert.ok(
    roster.length > 0,
    'game.items is empty, so every linked-Item resolution in the lab silently falls back',
  );
  assert.ok(
    roster.every((document) => String(document?.uuid ?? '').startsWith('Item.')),
    'an Actor or Scene leaked into the world Item roster',
  );
  assert.equal(
    roster.find((document) => document.uuid === 'Item.lab-tool-warped-crucible') ?? null,
    null,
    'the dangling-link fixture must NOT resolve, or ItemDropZone can never draw `missing`',
  );
});

function fixtureFunction(file, name, dependencies = {}) {
  const source = readFileSync(new URL(file, import.meta.url), 'utf8');
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start >= 0, `${file} declares ${name}`);
  const end = source.indexOf('\n}', start) + 2;
  assert.ok(end > start, `${name} has a complete body`);
  return new Function(...Object.keys(dependencies), `return (${source.slice(start, end)});`)(
    ...Object.values(dependencies)
  );
}

function journalFixture(state) {
  const seeded = structuredClone(buildLabContent({ journalCaseState: state }));
  const mode = { 'gathering-straight': 'straight', 'gathering-check': 'routed' }[state];
  if (mode) {
    fixtureFunction('./view-lab/world/labWorld.js', 'seedGatheringTaskMode', { LAB_SYSTEM_IDS })(seeded, mode);
  }
  const actor = buildLabActors(seeded)[0];
  const recipes = seeded.recipes.map((entry) => new Recipe(entry));
  const containers = buildLabRunStates({
    actor, userId: 'user-lab-player', recipes, environments: seeded.environments,
    tasks: seeded.gatheringConfig.tasks, journalCaseState: state,
  });
  return { actor, recipes, containers };
}

test('alchemy Journal uses an authored recipe revealed to its player, not a missing/redacted fallback', () => {
  const seeded = buildLabContent({ journalCaseState: 'alchemy' });
  const recipes = seeded.recipes.map((entry) => new Recipe(entry));
  const visibility = new RecipeVisibilityService(null, {
    getSystem: (id) => seeded.systems.find((entry) => entry.id === id),
  });
  const visible = recipes.filter((recipe) => visibility.evaluateRecipeAccess({
    recipe, viewer: { id: 'user-lab-player', isGM: false }, craftingActor: actors[0],
  }).visible);
  const containers = buildLabRunStates({
    actor: actors[0], userId: 'user-lab-player', recipes: visible,
    environments: seeded.environments, journalCaseState: 'alchemy',
  });
  const run = containers.craftingRuns.active['lab-v1-alchemy'];
  assert.equal(run.recipeId, 'al-r-fire');
  assert.deepEqual(
    recipes.filter((recipe) => recipe.craftingSystemId === LAB_SYSTEM_IDS.ALCHEMY).map((recipe) => recipe.id),
    ['al-r-fire', 'al-r-acid', 'al-r-smokestick', 'al-r-elixir', 'al-r-phoenix']
  );
  assert.equal(visible.filter((recipe) => recipe.craftingSystemId === LAB_SYSTEM_IDS.ALCHEMY).length, 1);
  assert.deepEqual(new Recipe(buildLabContent().recipes.find((recipe) => recipe.id === run.recipeId)).access.playerIds, []);
});

test('fixture commands refresh all real manager caches after flags move active runs to history', async () => {
  const recipes = content.recipes.map((entry) => new Recipe(entry));
  const actor = buildLabActors(content)[0];
  const containers = buildLabRunStates({
    actor, userId: 'user-lab-player', recipes, environments: content.environments,
    tasks: content.gatheringConfig.tasks,
  });
  const salvage = containers.salvageRuns.history.shift();
  salvage.status = 'inProgress';
  containers.salvageRuns.active[salvage.id] = salvage;
  installLabRunStates(actor, containers);
  const fabricate = {
    craftingRunManager: new CraftingRunManager(),
    salvageRunManager: new SalvageRunManager(),
    gatheringRunManager: new GatheringRunManager(),
  };
  const invalidate = fixtureFunction('./view-lab/world/labWorld.js', 'invalidateJournalFixtureCaches');
  const controller = createLabJournalCaseController({
    actor, containers, recipes, state: 'ready-single',
    onPersist: () => invalidate(fabricate),
  });
  for (const [runType, manager] of Object.entries(fabricate).map(([key, manager]) => [key.replace('RunManager', ''), manager])) {
    const run = manager.getActiveRuns(actor)[0];
    assert.ok(run, `${runType} cache is populated before the command`);
    assert.equal((await controller.execute({ runType, runId: run.id, action: 'cancel' })).success, true);
    assert.ok(!manager.getActiveRun(actor, run.id), `${runType} must not retain the pre-command run`);
    assert.equal(manager.getRunHistory(actor).find((entry) => entry.id === run.id)?.status, 'cancelled');
  }
  const worldSource = readFileSync(new URL('./view-lab/world/labWorld.js', import.meta.url), 'utf8');
  assert.match(worldSource, /onPersist:\s*\(\) => invalidateJournalFixtureCaches\(fabricate\)/);
});

test('Journal error fixture refuses repeated initial loads and retries until explicit recovery', async () => {
  const install = fixtureFunction('./view-lab/mount.js', 'installJournalCaseServiceSeam');
  const listing = { activeRuns: [{ id: 'recovered' }] };
  const services = { listJournalForActor: async () => listing };
  install(services, 'error-retry');
  for (let attempt = 0; attempt < 4; attempt++) {
    await assert.rejects(services.listJournalForActor('actor'), /View Lab Journal load failure/);
  }
  services.recoverJournalCaseFixture();
  assert.equal(await services.listJournalForActor('actor'), listing);
  assert.equal(await services.listJournalForActor('actor'), listing);
});

test('every Journal state survives the real run-manager normalizers at its declared identity', () => {
  for (const [state, runId] of Object.entries(LAB_JOURNAL_CASE_STATE_RUN_IDS)) {
    const { actor, containers } = journalFixture(state);
    installLabRunStates(actor, containers);
    const managers = [new CraftingRunManager(), new SalvageRunManager(), new GatheringRunManager()];
    const normalized = managers.flatMap((manager) => [
      ...manager.getActiveRuns(actor), ...manager.getRunHistory(actor),
    ]);
    if (runId) assert.ok(normalized.some((run) => run.id === runId), `${state}: ${runId} survives normalization`);
    if (state === 'no-actor-empty') assert.equal(normalized.length, 0);
  }
});

test('finished gathering fixtures persist actual mode-specific awards and shared-roll evidence', async () => {
  const expected = {
    'gathering-straight': [['hb-emberbloom', 2]],
    'gathering-d100': [['hb-moonleaf', 2], ['hb-sunroot', 1]],
    'gathering-check': [['hb-emberbloom', 2]],
  };
  for (const [state, awards] of Object.entries(expected)) {
    const fixture = journalFixture(state);
    installLabRunStates(fixture.actor, fixture.containers);
    const manager = new GatheringRunManager();
    const run = manager.getActiveRuns(fixture.actor)[0];
    const controller = createLabJournalCaseController({
      ...fixture, state, onPersist: () => manager.invalidateCache(),
    });
    await controller.execute({ runType: 'gathering', runId: run.id, action: 'execute' });
    assert.equal(manager.getActiveRuns(fixture.actor).length, 0);
    const finished = manager.getRunHistory(fixture.actor)[0];
    assert.equal(finished.status, 'succeeded');
    assert.deepEqual(finished.createdResults.map((entry) => [entry.componentId, entry.quantity]), awards);
    if (state === 'gathering-straight') assert.equal(finished.checkResult ?? null, null);
    if (state === 'gathering-check') assert.equal(finished.checkResult.outcome, 'Abundant');
    if (state === 'gathering-d100') {
      assert.equal(finished.checkResult.roll, 25);
      assert.deepEqual(finished.checkResult.itemRows.map((row) => row.awarded), [true, true, false, false]);
      assert.ok(finished.checkResult.itemRows.every((row) => row.roll === finished.checkResult.roll));
    }
    assert.equal(await controller.execute({ runType: 'gathering', runId: run.id, action: 'execute' }), undefined);
    assert.equal(manager.getRunHistory(fixture.actor).length, 1, 'terminal command cannot duplicate awards');
  }
});

test('command refusal fixtures preserve awards and report the reason the inline notice consumes', async () => {
  for (const [state, reason] of [['stale-action', 'stale-run'], ['command-timeout', 'command-timeout'], ['roll-cancelled', 'roll-cancelled']]) {
    const fixture = journalFixture(state);
    const run = Object.values(fixture.containers.craftingRuns.active)[0];
    const before = structuredClone(run);
    const controller = createLabJournalCaseController({ ...fixture, state });
    const result = await controller.execute({ runType: 'crafting', runId: run.id, action: 'execute' });
    assert.equal(result.success, false);
    assert.equal(result.reason, reason);
    assert.equal(fixture.containers.craftingRuns.history.length, 0);
    assert.deepEqual(run.steps, before.steps);
    assert.equal(run.runRevision, before.runRevision + (state === 'stale-action' ? 1 : 0));
    if (state === 'roll-cancelled') assert.equal(result.cancelled, true);
    else assert.ok(result.message.includes(reason), 'inline notice has the specific command failure');
  }
});
