/**
 * Every fixture identifier a case names must exist in the lab world.
 *
 * `tests/view-lab-cases.test.js` checks that a selector's HOOKS exist in `src/` — the class names
 * and attribute names — and it deliberately strips attribute VALUES before doing so, because those
 * values are fixture ids and live here rather than in `src/`. Nothing then checked them there. That
 * left the registry's largest hand-maintained mirror unguarded: roughly fifty component, recipe,
 * tool, task, event, environment and actor ids, plus every `query.system`.
 *
 * A renamed fixture id is caught today only by a capture run — which needs harvested Foundry chrome,
 * so it does not run on a fork PR, does not run without credentials, and is not part of `npm test`.
 * Between the rename and the next successful capture, the case silently cannot reach its state.
 *
 * The check is exact-value, not substring: `sm-longsword` must BE an id in the world, not merely
 * appear somewhere in the file. Substring matching is how the sibling guard in `view-lab-cases`
 * passed over six broken selectors before it was tightened.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import { VIEW_LAB_CASES } from '../scripts/lib/viewLabCases.js';
import { buildLabContent, LAB_SYSTEM_IDS } from './view-lab/world/labContent.js';
import { buildLabActors, buildDocumentIndex } from './view-lab/world/labActors.js';
import { stockJournalPrototype } from './view-lab/world/labJournalPrototype.js';
import {
  LAB_JOURNAL_CASE_STATE_RUN_IDS,
  buildLabRunStates,
  createLabJournalCaseController,
  installLabRunStates,
} from './view-lab/world/labRunStates.js';
import { Recipe } from '../src/models/Recipe.js';
import { RecipeVisibilityService } from '../src/systems/RecipeVisibilityService.js';
import { CraftingRunManager } from '../src/systems/CraftingRunManager.js';
import { SalvageRunManager } from '../src/systems/SalvageRunManager.js';
import { GatheringRunManager } from '../src/systems/GatheringRunManager.js';
import { RunJournalBuilder } from '../src/systems/RunJournalBuilder.js';
import { ResolutionModeService } from '../src/systems/ResolutionModeService.js';
import { installFoundryShim } from './view-lab/foundry/installFoundryShim.js';
import { installUpdateSemantics, makeGetFlag } from './view-lab/world/labFlags.js';
import { createFoundryJournalRunAuthority } from '../src/systems/journalRunAuthority.js';
import {
  createJournalRunCommandService,
  JOURNAL_RUN_SOCKET_KIND,
} from '../src/systems/journalRunCommands.js';

const content = buildLabContent();
const actors = buildLabActors(content);
installFoundryShim({
  documents: buildDocumentIndex(content, actors),
  content,
  actorList: actors,
  scenes: [],
  settings: new Map(),
  i18n: { localize: (key) => key },
  seed: {},
});

/** @returns {string[]} Run identities actually generated by the default and focused fixtures. */
function labRunIds() {
  return [null, ...Object.keys(LAB_JOURNAL_CASE_STATE_RUN_IDS)].flatMap((state) =>
    Object.values(journalFixture(state).containers).flatMap((container) =>
      [...Object.values(container.active), ...container.history].map((run) => run.id)
    )
  );
}

/**
 * Every modifier-library entry id the lab world declares.
 *
 * READ FROM THE AUTHORED SHAPE, not from `system.modifiers`. The fixture authors the library
 * where the pre-`1.23.0` world carried it — `craftingCheck.checkModifiers` — and the lab boot
 * runs every migration over it, so the key the DOM is eventually built from does not exist in
 * `buildLabContent()` at all. Deriving from `system.modifiers` produced an EMPTY set, which
 * then rejected every id a case legitimately names.
 *
 * @returns {string[]}
 */
function modifierLibraryIds() {
  return content.systems.flatMap((system) =>
    [
      ...(system.modifiers ?? []),
      ...(system.checkModifiers ?? []),
      ...(system.craftingCheck?.checkModifiers ?? []),
    ].map((entry) => entry.id)
  );
}

/** Attribute name -> the set of values the lab world actually contains. */
const IDENTITY_SOURCES = {
  'data-component-id': new Set(content.components.map((entry) => entry.id)),
  'data-recipe-id': new Set(content.recipes.map((entry) => entry.id)),
  'data-manager-tool-id': new Set(content.tools.map((entry) => entry.id)),
  'data-gathering-task-id': new Set(content.gatheringConfig.tasks.map((entry) => entry.id)),
  'data-task-id': new Set(content.gatheringConfig.tasks.map((entry) => entry.id)),
  'data-gathering-event-id': new Set(content.gatheringConfig.events.map((entry) => entry.id)),
  'data-environment-id': new Set(content.environments.map((entry) => entry.id)),
  'data-knowledge-actor': new Set(actors.map((entry) => entry.id)),

  // The ten below were the gap this file's own header describes and did not actually close. Each
  // pins a fixture id in a selector, so a rename is caught only by a capture run — which does not
  // run on fork PRs, and which is the slowest possible place to learn about a typo.
  'data-recipe-edit': new Set(content.recipes.map((entry) => entry.id)),
  'data-component-select': new Set(content.components.map((entry) => entry.id)),
  // The recipe browser's bulk selection control (issue 1010) — the exact mirror of
  // `data-component-select` above, and unguarded until now: the three
  // `manager-recipes-bulk-edit*` cases pin fixture ids in their row clicks, so a rename
  // would otherwise surface only in a capture run.
  'data-recipe-select': new Set(content.recipes.map((entry) => entry.id)),
  'data-system-id': new Set(content.systems.map((entry) => entry.id)),
  // The system Modifiers card's per-entry row and its roll note (issue 1118). Both pin a
  // library entry id, and `manager-system-edit-modifier-rolls` opens one by id in its steps and
  // asserts the note by id in its `expectSelector` — so a renamed entry would break the case in
  // two places and be caught by neither until a capture run.
  'data-world-modifier': new Set(modifierLibraryIds()),
  'data-world-modifier-roll-note': new Set(modifierLibraryIds()),
  // The essence browser's bulk selection control (issue 1036) — the exact mirror of
  // `data-component-select` and `data-recipe-select` above. The essence bulk-edit case pins
  // fixture ids in its row ticks, so a rename would otherwise surface only in a capture run.
  // Derived from the SYSTEM's declared vocabulary for the same reason `data-essence-id` is:
  // deriving it from the essences components happen to carry would falsely reject a
  // declared-but-uncarried essence.
  'data-essence-select': new Set(
    content.systems.flatMap((system) =>
      (system.essenceDefinitions ?? []).map((essence) => essence.id)
    )
  ),
  // From the SYSTEM's declared vocabulary, which is what `adminStore` builds the browser's rows
  // from and therefore what `EssenceBrowserView` writes into the attribute. Deriving these from the
  // essences components happen to carry passes today only because the two coincide: it would
  // falsely reject a declared-but-uncarried essence (the fixture authors exactly that deliberately
  // for the `runic` TAG) and falsely accept an essence key typo'd onto a component.
  'data-essence-id': new Set(
    content.systems.flatMap((system) =>
      (system.essenceDefinitions ?? []).map((essence) => essence.id)
    )
  ),
  // Also system-declared. `content.recipeItems` is the herbalism list alone, so smithing's
  // inline `sm-book` was missing from the set and a case naming it would have been rejected.
  'data-books-scrolls-edit': new Set(
    content.systems.flatMap((system) =>
      (system.recipeItemDefinitions ?? []).map((entry) => entry.id)
    )
  ),
  // Generated ids include paginated siblings and the blind run's shared constant.
  'data-history-run-id': new Set(labRunIds()),
  // The ACTIVE-run counterpart, carried by `RunCard`. Unguarded until issue 901's blind Journal
  // cases needed it, which is the same gap `labRunIds` above describes from the other end.
  'data-run-id': new Set(labRunIds()),
  // Composite keys. The listing builds these itself, so the guard has to build them the same way
  // or it would reject the very values the DOM carries.
  'data-inventory-card': new Set(
    content.systems.flatMap((system) =>
      (system.components ?? []).map((component) => `${system.id}:${component.id}`)
    )
  ),
  // The carrier's key is `item.uuid || item.id`, and an owned item's uuid is the component's
  // `originItemUuid` — which `component()` DEFAULTS to `Item.<id>` but two components override to
  // a shared uuid. Rebuilding the default instead of reading the field admitted a value the DOM
  // never carries and rejected the one it does.
  'data-essence-carrier': new Set(
    content.components.map((entry) => entry.originItemUuid ?? `Item.${entry.id}`)
  ),
};

/** Every `key="value"` pair in a selector, in source order. */
function attributePairs(selector) {
  return [...selector.matchAll(/\[([a-z][\w-]*)\s*=\s*"([^"]*)"\]/g)].map((match) => ({
    name: match[1],
    value: match[2],
  }));
}

/**
 * The identifier pins in a selector that `IDENTITY_SOURCES` recognises, each marked with whether
 * its value exists in the lab world.
 *
 * A pin whose attribute name `IDENTITY_SOURCES` does not recognise, or whose value is empty, is not
 * returned at all — the caller never sees it, exactly as the original step loop silently skipped it.
 * Both the step sweep and the `expectSelector` sweep below call this so their extraction and
 * matching cannot drift apart.
 *
 * @param {string} selector
 * @returns {{name: string, value: string, known: boolean}[]}
 */
function identifierPins(selector) {
  const pins = [];
  for (const { name, value } of attributePairs(selector)) {
    const source = IDENTITY_SOURCES[name];
    if (!source || value === '') continue;
    pins.push({ name, value, known: source.has(value) });
  }
  return pins;
}

// `data-popover-option` is deliberately absent from IDENTITY_SOURCES, and the widening it was
// left out FOR has since happened. The attribute has one producer, `SearchablePopover.svelte`,
// which stamps it for any option carrying a `dataId`; when this note was written one caller
// supplied one — `RecipeBulkEditPanel.svelte`, with `dataId: book.id` — so its whole value space
// was recipe book ids, and the component's own contract already named the Travel tab's pickers as
// the intended adopters: an option needs an identity handle because "without one the only handle is
// the display label, which is localized and therefore not a selector".
//
// Issue 1504 widened it much further than that. `Select` stamps EVERY row, so the attribute now
// carries page sizes, recipe categories, scoped-list sort keys and check-tier ids
// beside the book ids — none of them a lab-world record, several not identifiers at all.
// A source set defined from recipe book ids would by now falsely reject eleven legitimate steps
// across ten cases, which is exactly what the absence is here to prevent (issue #1021).
//
// Twenty of the twenty-five `expectSelector`-bearing cases key on an attribute IDENTITY_SOURCES does
// not recognise — `data-bulk-book-state`, `data-essence-view`, `data-inventory-bulk-panel`,
// `data-inventory-bulk-queue-row`, and others — and fall through `identifierPins`'s skip for the
// same reason a step naming one of those attributes would. Widening IDENTITY_SOURCES to cover them
// is out of scope here (issue #1021); this sweep only guards the five that already resolve.

test('every query.system names a real lab crafting system', () => {
  const known = new Set(Object.values(LAB_SYSTEM_IDS));
  const unknown = [];
  for (const viewCase of VIEW_LAB_CASES) {
    const system = viewCase.query?.system;
    if (system && !known.has(system)) unknown.push(`${viewCase.id}: ${system}`);
  }
  assert.deepEqual(
    unknown,
    [],
    'these cases open on a crafting system the lab world does not define, so the manager falls back ' +
      'to whichever system it had and the case photographs the wrong one:\n  ' +
      unknown.join('\n  ')
  );
});

test('every fixture id a selector names exists in the lab world', () => {
  const unknown = [];
  for (const viewCase of VIEW_LAB_CASES) {
    for (const step of viewCase.steps ?? []) {
      if (typeof step !== 'object') continue;
      for (const pin of identifierPins(step.selector)) {
        if (!pin.known) unknown.push(`${viewCase.id}: [${pin.name}="${pin.value}"]`);
      }
    }
  }
  assert.deepEqual(
    unknown,
    [],
    'these selectors name a fixture the lab world does not contain, so the step matches nothing and ' +
      'the case cannot reach its state. Either the fixture was renamed or the case was:\n  ' +
      unknown.join('\n  ')
  );
});

test('every fixture id an expectSelector names exists in the lab world', () => {
  const unknown = [];
  let recognized = 0;
  for (const viewCase of VIEW_LAB_CASES) {
    if (typeof viewCase.expectSelector !== 'string') continue;
    for (const pin of identifierPins(viewCase.expectSelector)) {
      recognized++;
      if (!pin.known) unknown.push(`${viewCase.id}: [${pin.name}="${pin.value}"]`);
    }
  }

  // This sweep is prospective: today every recognised expectSelector pin duplicates a value its own
  // case's steps already pinned, so a rename is caught by the step sweep first. A guard that
  // currently catches nothing needs a guard of its own, because one wired to the wrong field or run
  // over an always-empty collection passes exactly as loudly as a correct one. Counting the pins
  // the loop above actually visited, rather than recomputing them here, is what makes that visible.
  assert.ok(
    recognized > 0,
    'this sweep visited no expectSelector pin IDENTITY_SOURCES recognises, so the assertion below ' +
      'would pass even if every case were pinned to a nonexistent fixture'
  );

  assert.deepEqual(
    unknown,
    [],
    "these expectSelectors (not steps) name a fixture the lab world does not contain, so the case's " +
      'own state assertion matches nothing even after the case reaches it. Either the fixture was ' +
      'renamed or the expectSelector was:\n  ' +
      unknown.join('\n  ')
  );
});

test('the identity sources are populated, so the checks above are not vacuous', () => {
  // A builder that returned nothing would make every assertion above pass by matching an empty set
  // against an empty set — the shape of failure this whole file exists to catch, turned on itself.
  for (const [name, values] of Object.entries(IDENTITY_SOURCES)) {
    assert.ok(values.size > 0, `no lab fixture supplies values for ${name}`);
  }
  assert.ok(Object.values(LAB_SYSTEM_IDS).length >= 5, 'expected one system per resolution mode');
});

/**
 * The lab world Item roster reaches `game.items`, which is the collection the product reads.
 *
 * `buildDocumentIndex` has always minted an Item per component, tool and recipe item, but the
 * shim built `game.items` as an EMPTY collection and only appended what a frame created at
 * runtime. `getWorldItemOptions` in `SvelteCraftingSystemManagerApp.svelte.js` maps that
 * collection directly, so every screen resolving a linked game-world Item was photographed
 * against a roster no GM has.
 *
 * It was invisible in both directions. `toolSourceSnapshot` falls back
 * `worldItem || managedItem || tool`, so a linked tile drew the TOOL's own name and art and
 * looked entirely correct while never exercising the resolved-Item path. And `sourceMissing`
 * requires a NON-EMPTY roster by design — a roster that has not loaded must not read as a broken
 * link — so `ItemDropZone`'s `missing` face could not render in the lab at all, and the case
 * written for it failed the whole capture rather than one frame.
 *
 * This asserts the wiring, not a count: a non-empty roster, every entry an Item, and a uuid the
 * index does not mint answering nothing. The third is what the `missing` face depends on.
 */
test('the lab seeds game.items from the document index, Items only', async () => {
  const { installFoundryShim } = await import('./view-lab/foundry/installFoundryShim.js');
  const documents = buildDocumentIndex(content, actors);
  installFoundryShim({
    documents,
    content,
    actorList: actors,
    scenes: [],
    settings: new Map(),
    i18n: { localize: (key) => key },
    seed: {},
  });
  const roster = globalThis.game.items.contents;
  assert.ok(
    roster.length > 0,
    'game.items is empty, so every linked-Item resolution in the lab silently falls back'
  );
  assert.ok(
    roster.every((document) => String(document?.uuid ?? '').startsWith('Item.')),
    'an Actor or Scene leaked into the world Item roster'
  );
  assert.equal(
    roster.find((document) => document.uuid === 'Item.lab-tool-warped-crucible') ?? null,
    null,
    'the dangling-link fixture must NOT resolve, or ItemDropZone can never draw `missing`'
  );
});

function fixtureFunction(file, name, dependencies = {}) {
  const source = readFileSync(new URL(file, import.meta.url), 'utf8');
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start >= 0, `${file} declares ${name}`);
  const end = source.indexOf('\n}', start) + 2;
  assert.ok(end > start, `${name} has a complete body`);
  return new Function(...Object.keys(dependencies), `return (${source.slice(start, end)});`)(
    ...Object.values(dependencies)
  );
}

function journalFixture(state) {
  const seeded = structuredClone(buildLabContent({ journalCaseState: state }));
  const mode = { 'gathering-straight': 'straight', 'gathering-check': 'routed' }[state];
  if (mode) {
    fixtureFunction('./view-lab/world/labWorld.js', 'seedGatheringTaskMode', { LAB_SYSTEM_IDS })(
      seeded,
      mode
    );
  }
  const actor = buildLabActors(seeded)[0];
  const recipes = seeded.recipes.map((entry) => new Recipe(entry));
  const containers = buildLabRunStates({
    actor,
    userId: 'user-lab-player',
    recipes,
    environments: seeded.environments,
    tasks: seeded.gatheringConfig.tasks,
    journalCaseState: state,
  });
  return { actor, recipes, containers, seeded };
}

function journalProjection(
  state,
  viewer = { id: 'user-lab-player', isGM: false },
  fixture = journalFixture(state)
) {
  const { actor, recipes, containers, seeded } = fixture;
  installLabRunStates(actor, containers);
  const getSystem = (id) => seeded.systems.find((entry) => entry.id === id);
  const builder = new RunJournalBuilder({
    craftingRunManager: new CraftingRunManager(),
    salvageRunManager: new SalvageRunManager(),
    gatheringRunSource: new GatheringRunManager(),
    recipeManager: { getRecipe: (id) => recipes.find((recipe) => recipe.id === id) },
    recipeVisibility: new RecipeVisibilityService(null, { getSystem }),
    resolutionModeService: new ResolutionModeService({ getSystem }),
    getSystem,
    getComponent: (systemId, id) =>
      getSystem(systemId)?.components.find((entry) => entry.id === id),
    getGatheringTask: (_environmentId, taskId) =>
      seeded.gatheringConfig.tasks.find((task) => task.id === taskId),
    nowWorldTime: () => 1_209_600,
  });
  return builder.buildListing({ actor, viewer });
}

test('compact history witnesses have real short last pages, five long-name materials and distinct tool images', () => {
  for (const state of ['history-compact-grid', 'history-compact-tools']) {
    const listing = journalProjection(state);
    assert.equal(listing.activeRuns.length, 11);
    assert.equal(listing.history.length, 11);
    const run = listing.history.find((entry) => entry.id === `lab-v1-${state}`);
    assert.equal(run.steps[0].consumedIngredients.length, 5);
    assert.equal(run.steps[0].createdResults.length, 5);
    assert.ok(run.steps[0].consumedIngredients.every((entry) => entry.name.length > 70));
    assert.equal(new Set(run.steps[0].usedTools.map((entry) => entry.img)).size, 5);
    if (state === 'history-compact-tools') {
      assert.equal(run.steps[0].usedTools[0].itemUuid, run.steps[1].usedTools[0].itemUuid);
      assert.equal(run.steps[1].usedTools[0].broken, true);
    }
  }
});

test('ordinary future Journal stages contain no executed check or completion evidence', () => {
  const { containers } = journalFixture('future-stage');
  const run = Object.values(containers.craftingRuns.active).find(
    (entry) => entry.id === LAB_JOURNAL_CASE_STATE_RUN_IDS['future-stage']
  );
  for (const future of run.steps.slice(run.currentStepIndex + 1)) {
    assert.equal(future.status, 'pending');
    assert.ok(!future.lastCheckResult && !future.completedAt && !future.failureReason);
    assert.deepEqual(future.createdResults, []);
  }
});

test('whole-Journal parity starts with eleven active and twelve finished persisted accounts', () => {
  const { containers } = journalFixture('ready-single');
  assert.equal(
    Object.values(containers).reduce((sum, entry) => sum + Object.keys(entry.active).length, 0),
    11
  );
  assert.equal(
    Object.values(containers).reduce((sum, entry) => sum + entry.history.length, 0),
    12
  );
});

test('Journal parity content is opt-in and never mutates the default manager/crafting corpus', () => {
  const before = JSON.stringify(buildLabContent());
  for (const state of Object.keys(LAB_JOURNAL_CASE_STATE_RUN_IDS)) journalFixture(state);
  assert.equal(JSON.stringify(buildLabContent()), before);
  assert.ok(!buildLabContent().recipes.some((entry) => entry.id.startsWith('jp-recipe-')));
});

test('the prototype multistage accounts retain distinct inputs, awards and one shared physical carrier', () => {
  for (const [state, expected] of [
    [
      'history-multi-essence',
      [
        ['jp-macerate', 1],
        ['jp-clarity_tonic', 1],
      ],
    ],
    ['history-multi-shared-essence', [null, ['jp-prismatic_sigil', 1]]],
  ]) {
    const { containers } = journalFixture(state);
    const run = containers.craftingRuns.history[0];
    assert.equal(run.steps.length, 2);
    assert.deepEqual(
      run.steps.map((entry) =>
        entry.createdResults.length
          ? [entry.createdResults[0].componentId, entry.createdResults[0].quantity]
          : null
      ),
      expected
    );
    assert.notDeepEqual(run.steps[0].consumedIngredients, run.steps[1].consumedIngredients);
    assert.ok(
      run.steps.every((entry) => entry.presentationSnapshot.name && entry.resolutionSnapshot)
    );
    const projected = journalProjection(state).history.find((entry) => entry.id === run.id);
    assert.equal(projected.steps.length, 2);
    assert.deepEqual(projected.steps[1].currencySpends, []);
    if (state === 'history-multi-shared-essence') {
      const carriers = projected.steps[1].essenceSpend.carriers.filter(
        (entry) => entry.itemUuid === 'Item.jp-duskglass'
      );
      assert.equal(carriers.length, 1);
      assert.equal(carriers[0].quantity, 2);
      assert.deepEqual(carriers[0].contributions, [
        { essenceId: 'radiant', amount: 2 },
        { essenceId: 'shadow', amount: 4 },
      ]);
    }
  }
});

test('future authored stages acquire preview projections only after the builder, never in persisted fixtures', () => {
  for (const state of ['future-stage', 'future-routed-stage']) {
    const fixture = journalFixture(state);
    const run = fixture.containers.craftingRuns.active[LAB_JOURNAL_CASE_STATE_RUN_IDS[state]];
    const future = run.steps.at(-1);
    assert.ok(!Object.hasOwn(future, 'yieldPreview') && !Object.hasOwn(future, 'craftingYield'));
    assert.ok(!future.selectionPlan && !future.resolutionSnapshot && !future.lastCheckResult);
    const projected = journalProjection(state, undefined, fixture)
      .activeRuns.find((entry) => entry.id === run.id)
      .steps.at(-1);
    assert.equal(projected.yieldPreview.source, 'preview');
    assert.equal(projected.yieldPreview.stageIndex, run.steps.length - 1);
    assert.equal(projected.attempted, false);
  }
});

test('shared smoke Journal walk uses selection-button identity and composite detail keys', () => {
  const source = readFileSync(new URL('../scripts/foundry-test-run.mjs', import.meta.url), 'utf8');
  const start = source.indexOf('const journalActiveCard =');
  const end = source.indexOf('let journalErr =', start);
  assert.ok(start > 0 && end > start);
  const walk = source.slice(start, end);
  assert.ok(walk.includes('.journal-run-card[data-run-id]'));
  assert.ok(walk.includes('.journal-history-row [data-history-run-id]'));
  assert.ok(walk.includes('[data-journal-detail][data-run-key]'));
  assert.ok(walk.includes('[data-journal-history-detail]'));
  assert.doesNotMatch(
    walk,
    /\.journal-history-row\[|data-journal-detail\]\[data-run-id|data-run-type|data-journal-card="step-details"/
  );
});

test('route shortage and automatic open-choice blocker contain no spent material', () => {
  const { containers } = journalFixture('material-shortage');
  const run = containers.craftingRuns.active[LAB_JOURNAL_CASE_STATE_RUN_IDS['material-shortage']];
  assert.equal(run.steps[0].selectedRequirementSnapshot.name, 'Sunward warding');
  assert.equal(run.steps[0].selectedRequirementSnapshot.ingredientGroups[2].options[0].quantity, 2);
  assert.deepEqual(run.steps[0].consumedIngredients, []);
  const blocked =
    journalFixture('automatic-blocker').containers.craftingRuns.active['lab-v1-automatic-blocker'];
  assert.equal(blocked.completionMode, 'worldTime');
  assert.deepEqual(blocked.steps[blocked.currentStepIndex].consumedIngredients, []);
});

test('routed gathering fixture authors both success and failure outcomes for the whole ladder', () => {
  const { seeded } = journalFixture('gathering-check');
  const system = seeded.systems.find((entry) => entry.id === 'jp-system-gathering');
  const outcomes = system.gatheringCraftingCheck.routed.relativeOutcomes;
  assert.deepEqual(
    outcomes.map(({ name, success }) => [name, success]),
    [
      ['Barren', false],
      ['Meagre', true],
      ['Steady', true],
      ['Rich', true],
      ['Bountiful', true],
    ]
  );
  assert.ok(outcomes[0].dc < outcomes[1].dc, 'failure occupies the lower rolled band');
  const tiers = journalProjection('gathering-check').activeRuns.find(
    (entry) => entry.id === 'lab-v1-gathering-check'
  ).gatheringYield.tiers;
  assert.deepEqual(
    tiers.map(({ id, fail }) => [id, fail]),
    [
      ['barren', true],
      ['meagre', false],
      ['steady', false],
      ['rich', false],
      ['bountiful', false],
    ],
    'the real projection delivers both authored tiers to OutcomeLadder'
  );
});

test('redacted owner is versioned only in its lifecycle case; existing blind fixtures stay legacy', () => {
  const id = LAB_JOURNAL_CASE_STATE_RUN_IDS['redacted-owner'];
  const legacy = journalFixture(null).containers.gatheringRuns.active[id];
  const current = journalFixture('redacted-owner').containers.gatheringRuns.active[id];
  assert.equal(Object.hasOwn(legacy, 'lifecycleVersion'), false);
  assert.deepEqual(current, {
    ...legacy,
    lifecycleVersion: 1,
    runRevision: 0,
    completionMode: 'manual',
    pausedDurationSeconds: 0,
  });
  assert.ok(current.taskId.startsWith('blind:'));
  assert.equal(Object.hasOwn(current, 'economyEvidence'), false);
  const projected = journalProjection('redacted-owner').activeRuns[0];
  assert.equal(projected.actions.cancel, true);
  assert.equal(projected.gatheringYield, null);
});

test('legacy capture targets remain in the real Journal projection and on their initial pages', () => {
  const listing = journalProjection(null);
  const history = listing.history.toSorted((left, right) => right.finishedAt - left.finishedAt);
  assert.ok(history.slice(0, 4).some((run) => run.id === 'lab-run-succeeded-multi'));
  const detail = history.find((run) => run.id === 'lab-run-succeeded-multi');
  assert.ok(detail.steps.length > 1, 'legacy detail has a real multi-step recipe');
  assert.ok(listing.activeRuns.some((run) => run.id === 'lab-gathering-blind-waiting'));
  assert.ok(listing.activeRuns.length <= 4, 'legacy blind row needs no active-page navigation');
});

function installJournalTransport(game, service) {
  fixtureFunction('./view-lab/world/labWorld.js', 'installLabJournalTransport', {
    JOURNAL_RUN_SOCKET_KIND,
  })(game, service);
  return game.socket;
}

test('lab socket retains and disposes lifecycle listeners without echoing outbound Journal traffic', () => {
  const socket = installJournalTransport({}, {});
  const handler = () => assert.fail('an outbound emit must not echo to the local listener');
  const sibling = () => {};
  assert.equal(socket.on('module.fabricate', handler), socket);
  socket.on('module.fabricate', sibling).on('other-channel', handler);
  assert.deepEqual(socket.listeners('module.fabricate'), [handler, sibling]);
  socket.listeners('module.fabricate').pop();
  assert.deepEqual(
    socket.listeners('module.fabricate'),
    [handler, sibling],
    'inspection cannot dispose listeners'
  );
  assert.equal(socket.off('module.fabricate', handler), socket);
  assert.deepEqual(socket.listeners('module.fabricate'), [sibling]);
  assert.deepEqual(socket.listeners('other-channel'), [handler]);
  socket.off('module.fabricate', handler).off('module.fabricate');
  assert.deepEqual(socket.listeners('module.fabricate'), []);
  socket.off();
  assert.deepEqual(socket.listeners('other-channel'), []);
});

test('lab Journal replies honor recipient options and attest the GM before restoring the viewer', async () => {
  const player = { id: 'player' };
  const gm = { id: 'gm', isGM: true };
  const game = { user: player, users: { activeGM: gm } };
  const accepted = [];
  const delivered = [];
  const service = {
    handleSocketMessage: async (payload, senderId) => {
      delivered.push([payload.requestId, senderId, game.user.id]);
      game.socket.emit(
        'module.fabricate',
        {
          kind: JOURNAL_RUN_SOCKET_KIND.REPLY,
          requestId: payload.requestId,
          recipientId: player.id,
        },
        payload.replyOptions
      );
    },
    acceptReply: (payload, senderId) => accepted.push([payload.requestId, senderId, game.user.id]),
  };
  const socket = installJournalTransport(game, service);
  socket.on('module.fabricate', () =>
    assert.fail('the explicit GM transport owns Journal delivery')
  );
  for (const [requestId, replyOptions] of [
    ['wrong-recipient', { recipients: ['other'] }],
    ['no-recipients', { recipients: [] }],
    ['targeted', { recipients: [player.id] }],
    ['broadcast', undefined],
  ]) {
    socket.emit('module.fabricate', {
      kind: JOURNAL_RUN_SOCKET_KIND.REQUEST,
      requestId,
      senderId: 'forged',
      replyOptions,
    });
  }
  await new Promise((resolve) => setImmediate(resolve));
  assert.deepEqual(
    delivered,
    ['wrong-recipient', 'no-recipients', 'targeted', 'broadcast'].map((id) => [
      id,
      player.id,
      gm.id,
    ])
  );
  assert.deepEqual(accepted, [
    ['targeted', gm.id, player.id],
    ['broadcast', gm.id, player.id],
  ]);
  assert.equal(game.user, player);
});

test('lab authority transport runs real prepare/resolve commands and restores the player before prompting/posting', async () => {
  const ledger = fixtureFunction('./view-lab/world/labWorld.js', 'createLabRunAuthorityLedger', {
    installUpdateSemantics,
    makeGetFlag,
  })();
  const player = { id: 'player', isGM: false };
  const gm = { id: 'gm', isGM: true };
  const game = { user: gm, users: { activeGM: gm }, journal: [ledger] };
  const actor = { uuid: 'Actor.lab', testUserPermission: (user) => user === player };
  const run = { id: 'run', lifecycleVersion: 1, runRevision: 0 };
  const authority = createFoundryJournalRunAuthority({
    game,
    reconstructExecutions: async () => ({ success: true }),
  });
  let prompts = 0;
  let executions = 0;
  const service = createJournalRunCommandService({
    authority,
    currentUser: () => game.user,
    activeGM: () => gm,
    getUser: (id) => [player, gm].find((user) => user.id === id),
    resolveUuid: async () => actor,
    emit: (...args) => game.socket.emit('module.fabricate', ...args),
    randomId: () => crypto.randomUUID(),
    promptCheck: async () => {
      assert.equal(game.user, player, 'prompt runs in the initiating player context');
      assert.equal(ledger.pages.size, 0, 'prepare releases its claim before the player prompt');
      prompts++;
      return { confirmed: true };
    },
    postRollHandoff: async () => assert.equal(game.user, player),
    operations: {
      crafting: {
        getRun: async () => run,
        describeCheck: async () => ({ required: true, publicPrompt: { label: 'Craft' } }),
        evaluateCheck: async () => ({
          engineEvaluated: true,
          success: true,
          rollHandoff: { total: 17 },
        }),
        execute: async ({ executionGrant, sender }) => {
          assert.equal(game.user, gm);
          assert.equal(sender, player, 'ownership remains sender-scoped');
          assert.ok(authority.consumeExecutionGrant(executionGrant, { operation: 'execute' }));
          executions++;
          return { success: true };
        },
      },
    },
  });
  const socket = installJournalTransport(game, service);
  // Ready replay registers this local route. The simulated remote GM must not
  // execute through both it and the adapter's explicit awaited service call.
  const localRoute = (payload, senderId) => service.handleSocketMessage(payload, senderId);
  socket.on('module.fabricate', localRoute);
  assert.equal((await service.bootstrapJournalRunAuthority()).success, true);
  game.user = player;
  const result = await service.executeJournalRunCommand({
    actorUuid: actor.uuid,
    runType: 'crafting',
    runId: run.id,
    expectedRevision: 0,
    action: 'execute',
  });
  assert.equal(result.success, true);
  assert.equal(prompts, 1);
  assert.equal(executions, 1);
  assert.equal(game.user, player);
  assert.equal(ledger.pages.size, 0);
  assert.ok(
    Object.values(ledger.getFlag('fabricate', 'journalRunAuthorityState').requests).every(
      (request) => request.status === 'settled'
    )
  );
  socket.off('module.fabricate', localRoute);
  assert.deepEqual(socket.listeners('module.fabricate'), []);
});

test('alchemy Journal uses a supplied authored recipe revealed to its player, not a missing/redacted fallback', async () => {
  const seeded = buildLabContent({ journalCaseState: 'alchemy' });
  const actor = buildLabActors(seeded)[0];
  const recipes = seeded.recipes.map((entry) => new Recipe(entry));
  const visibility = new RecipeVisibilityService(null, {
    getSystem: (id) => seeded.systems.find((entry) => entry.id === id),
  });
  const visible = recipes.filter(
    (recipe) =>
      visibility.evaluateRecipeAccess({
        recipe,
        viewer: { id: 'user-lab-player', isGM: false },
        craftingActor: actor,
      }).visible
  );
  const containers = buildLabRunStates({
    actor,
    userId: 'user-lab-player',
    recipes: visible,
    environments: seeded.environments,
    journalCaseState: 'alchemy',
  });
  const run = containers.craftingRuns.active['lab-v1-alchemy'];
  assert.equal(run.recipeId, 'al-r-fire');
  const ingredientSet = recipes.find((recipe) => recipe.id === run.recipeId).ingredientSets[0];
  const matches = (option, held) =>
    seeded.components.find((entry) => entry.id === option.match.componentId)?.originItemUuid ===
    held.uuid;
  const resolveSelection = () => ingredientSet.resolveIngredientSelection(actor.items, matches);
  assert.equal(resolveSelection().success, false, 'the default smith has no alchemy reagents');
  await stockJournalPrototype(actor, seeded);
  assert.equal(resolveSelection().success, false, 'stocking is opt-in for this retained mode');
  await stockJournalPrototype(actor, seeded, 'alchemy');
  assert.equal(resolveSelection().success, true, 'the actual Journal actor can supply every group');
  assert.deepEqual(
    actor.items
      .filter((held) => ingredientSet.ingredients.some((option) => matches(option, held)))
      .map((held) => [held.uuid, held.system.quantity]),
    [
      ['Item.al-sulphur', 2],
      ['Item.al-quicksilver', 1],
      ['Item.al-flask', 1],
    ]
  );
  assert.deepEqual(
    recipes
      .filter((recipe) => recipe.craftingSystemId === LAB_SYSTEM_IDS.ALCHEMY)
      .map((recipe) => recipe.id),
    ['al-r-fire', 'al-r-acid', 'al-r-smokestick', 'al-r-elixir', 'al-r-phoenix']
  );
  assert.equal(
    visible.filter((recipe) => recipe.craftingSystemId === LAB_SYSTEM_IDS.ALCHEMY).length,
    1
  );
  assert.deepEqual(
    new Recipe(buildLabContent().recipes.find((recipe) => recipe.id === run.recipeId)).access
      .playerIds,
    []
  );
});

test('fixture commands refresh all real manager caches after flags move active runs to history', async () => {
  const recipes = content.recipes.map((entry) => new Recipe(entry));
  const actor = buildLabActors(content)[0];
  const containers = buildLabRunStates({
    actor,
    userId: 'user-lab-player',
    recipes,
    environments: content.environments,
    tasks: content.gatheringConfig.tasks,
  });
  const salvage = containers.salvageRuns.history.shift();
  salvage.status = 'inProgress';
  containers.salvageRuns.active[salvage.id] = salvage;
  installLabRunStates(actor, containers);
  const fabricate = {
    craftingRunManager: new CraftingRunManager(),
    salvageRunManager: new SalvageRunManager(),
    gatheringRunManager: new GatheringRunManager(),
  };
  const invalidate = fixtureFunction(
    './view-lab/world/labWorld.js',
    'invalidateJournalFixtureCaches'
  );
  const controller = createLabJournalCaseController({
    actor,
    containers,
    recipes,
    state: 'ready-single',
    onPersist: () => invalidate(fabricate),
  });
  for (const [runType, manager] of Object.entries(fabricate).map(([key, manager]) => [
    key.replace('RunManager', ''),
    manager,
  ])) {
    const run = manager.getActiveRuns(actor)[0];
    assert.ok(run, `${runType} cache is populated before the command`);
    assert.equal(
      (await controller.execute({ runType, runId: run.id, action: 'cancel' })).success,
      true
    );
    assert.ok(
      !manager.getActiveRun(actor, run.id),
      `${runType} must not retain the pre-command run`
    );
    assert.equal(
      manager.getRunHistory(actor).find((entry) => entry.id === run.id)?.status,
      'cancelled'
    );
  }
  const worldSource = readFileSync(
    new URL('./view-lab/world/labWorld.js', import.meta.url),
    'utf8'
  );
  assert.match(worldSource, /onPersist:\s*\(\) => invalidateJournalFixtureCaches\(fabricate\)/);
});

test('Journal error fixture refuses repeated initial loads and retries until explicit recovery', async () => {
  const install = fixtureFunction('./view-lab/mount.js', 'installJournalCaseServiceSeam');
  const listing = { activeRuns: [{ id: 'recovered' }] };
  const services = { listJournalForActor: async () => listing };
  install(services, 'error-retry');
  for (let attempt = 0; attempt < 4; attempt++) {
    await assert.rejects(services.listJournalForActor('actor'), /View Lab Journal load failure/);
  }
  services.recoverJournalCaseFixture();
  assert.equal(await services.listJournalForActor('actor'), listing);
  assert.equal(await services.listJournalForActor('actor'), listing);
});

test('every Journal state survives the real run-manager normalizers at its declared identity', () => {
  for (const [state, runId] of Object.entries(LAB_JOURNAL_CASE_STATE_RUN_IDS)) {
    const { actor, containers } = journalFixture(state);
    installLabRunStates(actor, containers);
    const managers = [new CraftingRunManager(), new SalvageRunManager(), new GatheringRunManager()];
    const normalized = managers.flatMap((manager) => [
      ...manager.getActiveRuns(actor),
      ...manager.getRunHistory(actor),
    ]);
    if (runId)
      assert.ok(
        normalized.some((run) => run.id === runId),
        `${state}: ${runId} survives normalization`
      );
    if (state === 'no-actor-empty') assert.equal(normalized.length, 0);
  }
});

test('finished gathering fixtures persist actual mode-specific awards and shared-roll evidence', async () => {
  const expected = {
    'gathering-straight': [
      ['jp-meadow_herb', 2],
      ['jp-springwater', 1],
    ],
    'gathering-d100': [
      ['jp-rough_stone', 6],
      ['jp-whetstone', 1],
    ],
    'gathering-check': [
      ['jp-balehound_hide', 1],
      ['jp-balehound_fang', 2],
      ['jp-acid_gland', 1],
    ],
  };
  for (const [state, awards] of Object.entries(expected)) {
    const fixture = journalFixture(state);
    installLabRunStates(fixture.actor, fixture.containers);
    const manager = new GatheringRunManager();
    const run = manager
      .getActiveRuns(fixture.actor)
      .find((entry) => entry.id === LAB_JOURNAL_CASE_STATE_RUN_IDS[state]);
    const controller = createLabJournalCaseController({
      ...fixture,
      state,
      onPersist: () => manager.invalidateCache(),
    });
    await controller.execute({ runType: 'gathering', runId: run.id, action: 'execute' });
    assert.equal(manager.getActiveRuns(fixture.actor).length, 2);
    const finished = manager.getRunHistory(fixture.actor)[0];
    assert.equal(finished.status, 'succeeded');
    assert.deepEqual(
      finished.createdResults.map((entry) => [entry.componentId, entry.quantity]),
      awards
    );
    if (state === 'gathering-straight') assert.equal(finished.checkResult ?? null, null);
    assert.deepEqual(
      finished.executionJournal.effects[0].receipt.map((entry) => [
        entry.componentId,
        entry.quantity,
      ]),
      awards
    );
    assert.equal(finished.executionJournal.effects[0].effectId, 'results');
    assert.equal(finished.executionJournal.effects[0].phase, 'applied');
    // Top-level results precede effects in v1 gathering and are merely planned.
    const stored = fixture.containers.gatheringRuns.history[0];
    stored.createdResults = [
      { componentId: 'jp-rough_stone', quantity: 999, name: 'PLANNED_ONLY_SENTINEL' },
    ];
    const projected = journalProjection(state, undefined, fixture).history.find(
      (entry) => entry.id === run.id
    );
    assert.equal(projected.gatheringYield.source, 'recorded');
    assert.deepEqual(
      projected.createdResults.map((entry) => [entry.componentId, entry.quantity]),
      awards
    );
    assert.ok(!JSON.stringify(projected).includes('PLANNED_ONLY_SENTINEL'));
    if (state === 'gathering-check') assert.equal(finished.checkResult.outcome, 'Rich');
    if (state === 'gathering-d100') {
      assert.equal(finished.checkResult.roll, 75);
      assert.deepEqual(
        finished.checkResult.itemRows.map((row) => row.dropped),
        [true, true, false]
      );
      assert.ok(
        finished.checkResult.itemRows.every(
          (row) =>
            row.effectiveRoll === finished.checkResult.roll &&
            row.threshold === 101 - row.finalDropRate
        )
      );
    }
    assert.equal(
      await controller.execute({ runType: 'gathering', runId: run.id, action: 'execute' }),
      undefined
    );
    assert.equal(
      manager.getRunHistory(fixture.actor).length,
      3,
      'terminal command cannot duplicate awards'
    );
  }
});

test('command refusal fixtures preserve awards and report the reason the inline notice consumes', async () => {
  for (const [state, reason] of [
    ['stale-action', 'stale-run'],
    ['command-timeout', 'command-timeout'],
    ['roll-cancelled', 'roll-cancelled'],
  ]) {
    const fixture = journalFixture(state);
    const run = Object.values(fixture.containers.craftingRuns.active)[0];
    const before = structuredClone(run);
    const controller = createLabJournalCaseController({ ...fixture, state });
    const result = await controller.execute({
      runType: 'crafting',
      runId: run.id,
      action: 'execute',
    });
    assert.equal(result.success, false);
    assert.equal(result.reason, reason);
    assert.equal(fixture.containers.craftingRuns.history.length, 0);
    assert.deepEqual(run.steps, before.steps);
    assert.equal(run.runRevision, before.runRevision + (state === 'stale-action' ? 1 : 0));
    if (state === 'roll-cancelled') assert.equal(result.cancelled, true);
    else
      assert.ok(result.message.includes(reason), 'inline notice has the specific command failure');
  }
});
