/**
 * The canonical View Lab case registry.
 *
 * One entry per captured PNG. A case names a WINDOW and the state to drive it to — not a component
 * — because the evidence a UI PR needs is "here is the screen you changed", and a screen is an
 * application window with its rail, its chrome, and its neighbours in frame.
 *
 * `sourceMatches` is what turns a diff into a capture list. Patterns are directory-anchored rather
 * than file-anchored: a window case is affected by anything under the view it renders. That creates
 * a fan-out hazard — an edit to a shared component or to `styles/` would otherwise select all
 * fourteen cases — so those broad signals deliberately map to a small representative set instead.
 * See {@link mapChangedFilesToCases}.
 */

const PLAYER = 'fabricate-app';
const MANAGER = 'fabricate-crafting-system-manager';

/**
 * Files that can change what a window looks like. Mirrors the rule in `AGENTS.md`: a `lang/` change
 * needs evidence only when the same PR also touches a render file, which callers enforce by testing
 * `hasUiChanges` over the whole changed set.
 */
const UI_PATH_PATTERN = /^(src\/ui\/|styles\/)|\.(svelte|css)$/;

/**
 * The harness's own inputs: the fixture world every frame renders from, the page that mounts it,
 * the Foundry shim it renders against, and this registry. None of these is a render file, so none
 * is selectable by {@link isUiFile} — but a change to any of them can move every frame at once.
 */
const LAB_INFRASTRUCTURE_PATTERN =
  /^(tests\/view-lab\/|scripts\/lib\/viewLabCases\.js$|scripts\/lib\/foundryChromeSpec\.js$|scripts\/view-lab-screenshots\.mjs$)/;

/**
 * Signals too broad to attribute to one window. A shared primitive or a global stylesheet can
 * affect every screen, so selecting every case would make the evidence set useless noise. These map
 * to the representative set below plus the fallback.
 */
/**
 * The MANAGER's own shared primitives — its equivalent of `src/ui/svelte/components/`.
 *
 * An explicit list rather than a directory glob, because `apps/manager/` mixes primitives with
 * feature views: a glob would swallow `RecipesBrowserView.svelte` too and route every manager
 * change to the representative set, destroying the targeting this registry exists for.
 */
const MANAGER_PRIMITIVES = [
  'ArmedDangerButton',
  'Callout',
  'Chip',
  'EditorValidationSurface',
  'EmptyState',
  'ExplainerCard',
  'IconFactRow',
  'ItemDropZone',
  'ManagerModal',
  'RadioCardGroup',
  'RollDataExpressionInput',
  'SearchablePopover',
  'SegmentedControl',
  'ToggleCard',
];

export const BROAD_SIGNAL_PATTERN = new RegExp(
  [
    '^styles/',
    '^src/ui/svelte/components/',
    String.raw`^src/ui/theme\.js$`,
    String.raw`^src/ui/svelte/apps/manager/(${MANAGER_PRIMITIVES.join('|')})\.svelte$`,
  ].join('|')
);

/** One player screen and one manager screen: enough to show a shared-primitive change in context. */
const REPRESENTATIVE_CASE_IDS = Object.freeze(['fabricate-app-shell', 'manager-components-normal']);

export const FALLBACK_CASE_ID = 'fabricate-app-shell';

export const VIEW_LAB_CASES = Object.freeze([
  {
    id: 'manager-recipes-editor-roundtrip',
    label: 'Manager — Recipes editor roundtrip',
    app: MANAGER,
    smokeLabels: ['manager-recipes-editor-roundtrip'],
    reaches: 'window',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-default-selection',
    label: 'Manager — Default selection',
    app: MANAGER,
    smokeLabels: ['manager-default-selection'],
    reaches: 'exact',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
      /^src\/ui\/svelte\/apps\/manager\/Systems?(Browser|Overview)View\.svelte$/,
    ],
  },
  {
    id: 'manager-selected-normal',
    label: 'Manager — Selected normal',
    app: MANAGER,
    smokeLabels: ['manager-selected-normal'],
    reaches: 'exact',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'manager-rail-expanded',
    label: 'Manager — Rail expanded',
    app: MANAGER,
    smokeLabels: ['manager-rail-expanded'],
    reaches: 'exact',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'manager-rail-collapsed',
    label: 'Manager — Rail collapsed',
    app: MANAGER,
    smokeLabels: ['manager-rail-collapsed'],
    reaches: 'exact',
    query: {},
    steps: [{ selector: '.manager-rail-toggle' }],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'manager-selected-stacked',
    label: 'Manager — Selected stacked',
    app: MANAGER,
    smokeLabels: ['manager-selected-stacked'],
    reaches: 'exact',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1000, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems', 'responsive'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'manager-system-edit-normal',
    label: 'Manager — System edit normal',
    app: MANAGER,
    smokeLabels: ['manager-system-edit-normal'],
    reaches: 'exact',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/(ResolutionModeCard|CraftingEffectPanel|ItemPageInspector)\.svelte$/,
    ],
  },
  {
    id: 'manager-system-edit-narrow',
    label: 'Manager — System edit narrow',
    app: MANAGER,
    smokeLabels: ['manager-system-edit-narrow'],
    reaches: 'exact',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 900, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'responsive'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'manager-system-edit-dirty',
    label: 'Manager — System edit dirty',
    app: MANAGER,
    smokeLabels: ['manager-system-edit-dirty'],
    reaches: 'window',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'manager-system-edit-lists',
    label: 'Manager — System edit lists',
    app: MANAGER,
    smokeLabels: ['manager-system-edit-lists'],
    reaches: 'window',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 980 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'currency-actor-property',
    label: 'Manager — Currency actor property',
    app: MANAGER,
    smokeLabels: ['currency-actor-property'],
    reaches: 'window',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'currency-macro',
    label: 'Manager — Currency macro',
    app: MANAGER,
    smokeLabels: ['currency-macro'],
    reaches: 'window',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'currency-actor-inventory',
    label: 'Manager — Currency actor inventory',
    app: MANAGER,
    smokeLabels: ['currency-actor-inventory'],
    reaches: 'window',
    query: {},
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system-edit', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/],
  },
  {
    id: 'manager-recipes-normal',
    label: 'Manager — Recipes normal',
    app: MANAGER,
    smokeLabels: ['manager-recipes-normal'],
    reaches: 'exact',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-recipes-narrow',
    label: 'Manager — Recipes narrow',
    app: MANAGER,
    smokeLabels: ['manager-recipes-narrow'],
    reaches: 'exact',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 900, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'responsive'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-recipes-no-check',
    label: 'Manager — Recipes no check',
    app: MANAGER,
    smokeLabels: ['manager-recipes-no-check'],
    reaches: 'window',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-recipes-grouped-continuation',
    label: 'Manager — Recipes grouped continuation',
    app: MANAGER,
    smokeLabels: ['manager-recipes-grouped-continuation'],
    reaches: 'window',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-crafting-group-expanded',
    label: 'Manager — Crafting group expanded',
    app: MANAGER,
    smokeLabels: ['manager-crafting-group-expanded'],
    reaches: 'exact',
    query: {},
    steps: ['Crafting'],
    expectView: 'recipes',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Recipe/,
      /^src\/ui\/svelte\/apps\/manager\/recipes?\//,
    ],
  },
  {
    id: 'manager-books-scrolls-normal',
    label: 'Manager — Books scrolls normal',
    app: MANAGER,
    smokeLabels: ['manager-books-scrolls-normal'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-books-scrolls' }],
    expectView: 'books-scrolls',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'books-scrolls'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/BooksScrollsView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe-item\//,
    ],
  },
  {
    id: 'manager-crafting-settings',
    label: 'Manager — Crafting settings',
    app: MANAGER,
    smokeLabels: ['manager-crafting-settings'],
    reaches: 'exact',
    query: {},
    steps: ['Crafting', { selector: '#manager-crafting-nav-settings' }],
    expectView: 'crafting-settings',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'crafting-settings'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/CraftingSettingsView\.svelte$/],
  },
  {
    id: 'manager-recipe-item-validation',
    label: 'Manager — Recipe item validation',
    app: MANAGER,
    smokeLabels: ['manager-recipe-item-validation'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-books-scrolls' }],
    expectView: 'books-scrolls',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'books-scrolls', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/BooksScrollsView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe-item\//,
    ],
  },
  {
    id: 'manager-recipe-item-validation-blocked',
    label: 'Manager — Recipe item validation blocked',
    app: MANAGER,
    smokeLabels: ['manager-recipe-item-validation-blocked'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-books-scrolls' }],
    expectView: 'books-scrolls',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'books-scrolls', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/BooksScrollsView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe-item\//,
    ],
  },
  {
    id: 'manager-recipe-edit-normal',
    label: 'Manager — Recipe edit normal',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-normal'],
    reaches: 'exact',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-overview' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-books-scrolls',
    label: 'Manager — Recipe edit books scrolls',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-books-scrolls'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-books-scrolls' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-tools',
    label: 'Manager — Recipe edit tools',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-tools'],
    reaches: 'exact',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-tools' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-ingredients',
    label: 'Manager — Recipe edit ingredients',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-ingredients'],
    reaches: 'exact',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-ingredients' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-ingredients-cost',
    label: 'Manager — Recipe edit ingredients cost',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-ingredients-cost'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-ingredients' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-validation',
    label: 'Manager — Recipe edit validation',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-validation'],
    reaches: 'exact',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-validation' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-multistep',
    label: 'Manager — Recipe edit multistep',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-multistep'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-overview' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-results',
    label: 'Manager — Recipe edit results',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-results'],
    reaches: 'exact',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-results-multistep',
    label: 'Manager — Recipe edit results multistep',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-results-multistep'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-multistep-disable-confirm',
    label: 'Manager — Multistep disable confirm',
    app: MANAGER,
    smokeLabels: ['manager-multistep-disable-confirm'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-overview' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-collapsed',
    label: 'Manager — Recipe edit collapsed',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-collapsed'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-overview' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-results-progressive',
    label: 'Manager — Recipe edit results progressive',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-results-progressive'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-results-alchemy',
    label: 'Manager — Recipe edit results alchemy',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-results-alchemy'],
    reaches: 'window',
    query: {},
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/RecipeEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
    ],
  },
  {
    id: 'manager-recipe-edit-access-rail',
    label: 'Manager — Recipe edit access rail',
    app: MANAGER,
    smokeLabels: ['manager-recipe-edit-access-rail'],
    reaches: 'exact',
    query: { system: 'lab-alchemy' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-access' }],
    expectView: 'access',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'access'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/AccessTabView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/GrantAccessInspector\.svelte$/,
    ],
  },
  {
    id: 'manager-components-normal',
    label: 'Manager — Components normal',
    app: MANAGER,
    smokeLabels: ['manager-components-normal'],
    reaches: 'exact',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-bulk-edit',
    label: 'Manager — Components bulk edit',
    app: MANAGER,
    smokeLabels: ['manager-components-bulk-edit'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-bulk-edit-unstaged',
    label: 'Manager — Components bulk edit unstaged',
    app: MANAGER,
    smokeLabels: ['manager-components-bulk-edit-unstaged'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-description-before',
    label: 'Manager — Components description before',
    app: MANAGER,
    smokeLabels: ['manager-components-description-before'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-description-repaired',
    label: 'Manager — Components description repaired',
    app: MANAGER,
    smokeLabels: ['manager-components-description-repaired'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-description-ingested',
    label: 'Manager — Components description ingested',
    app: MANAGER,
    smokeLabels: ['manager-components-description-ingested'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-component-edit-normal',
    label: 'Manager — Component edit normal',
    app: MANAGER,
    smokeLabels: ['manager-component-edit-normal'],
    reaches: 'exact',
    query: {},
    steps: ['Components', { selector: '.manager-icon-button[aria-label^="Edit"]' }],
    expectView: 'component-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ComponentEditView\.svelte$/],
  },
  {
    id: 'manager-component-edit-salvage',
    label: 'Manager — Component edit salvage',
    app: MANAGER,
    smokeLabels: ['manager-component-edit-salvage'],
    reaches: 'exact',
    query: {},
    steps: [
      'Components',
      {
        selector:
          '.manager-component-row[data-component-id="sm-longsword"] .manager-icon-button[aria-label^="Edit"]',
      },
    ],
    expectView: 'component-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ComponentEditView\.svelte$/],
  },
  {
    id: 'manager-component-edit-salvage-off',
    label: 'Manager — Component edit salvage off',
    app: MANAGER,
    smokeLabels: ['manager-component-edit-salvage-off'],
    reaches: 'exact',
    query: {},
    steps: [
      'Components',
      {
        selector:
          '.manager-component-row[data-component-id="sm-chainmail"] .manager-icon-button[aria-label^="Edit"]',
      },
    ],
    expectView: 'component-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ComponentEditView\.svelte$/],
  },
  {
    id: 'manager-component-edit-salvage-simple',
    label: 'Manager — Component edit salvage simple',
    app: MANAGER,
    smokeLabels: ['manager-component-edit-salvage-simple'],
    reaches: 'exact',
    query: {},
    steps: [
      'Components',
      {
        selector:
          '.manager-component-row[data-component-id="sm-longsword"] .manager-icon-button[aria-label^="Edit"]',
      },
    ],
    expectView: 'component-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ComponentEditView\.svelte$/],
  },
  {
    id: 'manager-checks-gathering',
    label: 'Manager — Checks gathering',
    app: MANAGER,
    smokeLabels: ['manager-checks-gathering'],
    reaches: 'exact',
    query: {},
    steps: ['Checks', { selector: '#checks-tab-gathering' }],
    expectView: 'checks',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'checks', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/checks\//,
      /^src\/ui\/svelte\/apps\/manager\/.*Check/,
    ],
  },
  {
    id: 'manager-checks-validation',
    label: 'Manager — Checks validation',
    app: MANAGER,
    smokeLabels: ['manager-checks-validation'],
    reaches: 'exact',
    query: {},
    steps: ['Checks', { selector: '#checks-tab-validation' }],
    expectView: 'checks',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'checks', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/checks\//,
      /^src\/ui\/svelte\/apps\/manager\/.*Check/,
    ],
  },
  {
    id: 'manager-checks-crafting-consumption',
    label: 'Manager — Checks crafting consumption',
    app: MANAGER,
    smokeLabels: ['manager-checks-crafting-consumption'],
    reaches: 'exact',
    query: {},
    steps: ['Checks', { selector: '#checks-tab-crafting' }],
    expectView: 'checks',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'checks'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/checks\//,
      /^src\/ui\/svelte\/apps\/manager\/.*Check/,
    ],
  },
  {
    id: 'manager-checks-crafting-modifiers',
    label: 'Manager — Checks crafting modifiers',
    app: MANAGER,
    smokeLabels: ['manager-checks-crafting-modifiers'],
    reaches: 'window',
    query: {},
    steps: ['Checks', { selector: '#checks-tab-crafting' }],
    expectView: 'checks',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'checks', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/checks\//,
      /^src\/ui\/svelte\/apps\/manager\/.*Check/,
    ],
  },
  {
    id: 'manager-components-stacked',
    label: 'Manager — Components stacked',
    app: MANAGER,
    smokeLabels: ['manager-components-stacked'],
    reaches: 'exact',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1000, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'responsive'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-grouped-continuation',
    label: 'Manager — Components grouped continuation',
    app: MANAGER,
    smokeLabels: ['manager-components-grouped-continuation'],
    reaches: 'window',
    query: {},
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-tags-categories-normal',
    label: 'Manager — Tags categories normal',
    app: MANAGER,
    smokeLabels: ['manager-tags-categories-normal'],
    reaches: 'exact',
    query: {},
    steps: ['Tags & Categories', { selector: '#vocabulary-tab-recipe' }],
    expectView: 'tags',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tags'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/TagsCategories/,
      /^src\/ui\/svelte\/apps\/manager\/(VocabularyPanel|InlineVocabularyAdd)\.svelte$/,
    ],
  },
  {
    id: 'manager-tags-categories-tags-tab',
    label: 'Manager — Tags categories tags tab',
    app: MANAGER,
    smokeLabels: ['manager-tags-categories-tags-tab'],
    reaches: 'exact',
    query: {},
    steps: ['Tags & Categories', { selector: '#vocabulary-tab-tag' }],
    expectView: 'tags',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tags', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/TagsCategories/],
  },
  {
    id: 'manager-tags-categories-stacked',
    label: 'Manager — Tags categories stacked',
    app: MANAGER,
    smokeLabels: ['manager-tags-categories-stacked'],
    reaches: 'exact',
    query: {},
    steps: ['Tags & Categories', { selector: '#vocabulary-tab-recipe' }],
    expectView: 'tags',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tags', 'responsive'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/TagsCategories/],
  },
  {
    id: 'manager-essences-normal',
    label: 'Manager — Essences normal',
    app: MANAGER,
    smokeLabels: ['manager-essences-normal'],
    reaches: 'exact',
    query: {},
    steps: ['Essences'],
    expectView: 'essences',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'essences'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/Essence/],
  },
  {
    id: 'manager-essences-stacked',
    label: 'Manager — Essences stacked',
    app: MANAGER,
    smokeLabels: ['manager-essences-stacked'],
    reaches: 'exact',
    query: {},
    steps: ['Essences'],
    expectView: 'essences',
    position: { width: 1000, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'essences', 'responsive'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/Essence/],
  },
  {
    id: 'manager-essence-edit-first-state',
    label: 'Manager — Essence edit first state',
    app: MANAGER,
    smokeLabels: ['manager-essence-edit-first-state'],
    reaches: 'window',
    query: {},
    steps: ['Essences', { selector: '.manager-icon-button[aria-label^="Edit"]' }],
    expectView: 'essence-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'essences', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/EssenceEditView\.svelte$/],
  },
  {
    id: 'manager-environments-browse-normal',
    label: 'Manager — Environments browse normal',
    app: MANAGER,
    smokeLabels: ['manager-environments-browse-normal'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
      /^src\/ui\/svelte\/apps\/manager\/environment\//,
    ],
  },
  {
    id: 'manager-environments-browse-stacked',
    label: 'Manager — Environments browse stacked',
    app: MANAGER,
    smokeLabels: ['manager-environments-browse-stacked'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1000, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'responsive'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-gathering-task-editor-normal',
    label: 'Manager — Gathering task editor normal',
    app: MANAGER,
    smokeLabels: ['manager-gathering-task-editor-normal'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-gathering-task-editor-stacked',
    label: 'Manager — Gathering task editor stacked',
    app: MANAGER,
    smokeLabels: ['manager-gathering-task-editor-stacked'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-environment-edit-placeholder',
    label: 'Manager — Environment edit placeholder',
    app: MANAGER,
    smokeLabels: ['manager-environment-edit-placeholder'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering', { selector: '.manager-icon-button[aria-label^="Edit"]' }],
    expectView: 'environment-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/EnvironmentEditView\.svelte$/],
  },
  {
    id: 'manager-gathering-events-normal',
    label: 'Manager — Gathering events normal',
    app: MANAGER,
    smokeLabels: ['manager-gathering-events-normal'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-gathering-event-editor-normal',
    label: 'Manager — Gathering event editor normal',
    app: MANAGER,
    smokeLabels: ['manager-gathering-event-editor-normal'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-gathering-travel-normal',
    label: 'Manager — Gathering travel normal',
    app: MANAGER,
    smokeLabels: ['manager-gathering-travel-normal'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
      /^src\/ui\/svelte\/apps\/manager\/(Party|Realm|RosterRow|MapRegionLinkPicker)/,
    ],
  },
  {
    id: 'manager-gathering-travel-stacked',
    label: 'Manager — Gathering travel stacked',
    app: MANAGER,
    smokeLabels: ['manager-gathering-travel-stacked'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Gathering'],
    expectView: 'environments',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'environments', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Environment/,
      /^src\/ui\/svelte\/apps\/manager\/Gathering/,
    ],
  },
  {
    id: 'manager-tool-parity-01-library-1280x720',
    label: 'Manager — Tool parity 01 library 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-01-library-1280x720'],
    reaches: 'exact',
    query: {},
    steps: ['Tools'],
    expectView: 'tools',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Tool/,
      /^src\/ui\/svelte\/apps\/manager\/tools\//,
    ],
  },
  {
    id: 'manager-tool-zero-state-empty-library-1280x720',
    label: 'Manager — Tool zero state empty library 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-zero-state-empty-library-1280x720'],
    reaches: 'exact',
    query: { system: 'lab-jewelry' },
    steps: ['Tools'],
    expectView: 'tools',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Tool/,
      /^src\/ui\/svelte\/apps\/manager\/tools\//,
    ],
  },
  {
    id: 'manager-tool-parity-02-overview-1280x720',
    label: 'Manager — Tool parity 02 overview 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-02-overview-1280x720'],
    reaches: 'exact',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-overview' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-long-name',
    label: 'Manager — Tool stress long name',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-long-name'],
    reaches: 'window',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-overview' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-parity-03-breakage-1280x720',
    label: 'Manager — Tool parity 03 breakage 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-03-breakage-1280x720'],
    reaches: 'exact',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-breakage' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-repair',
    label: 'Manager — Tool stress repair',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-repair'],
    reaches: 'window',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-breakage' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-replacement',
    label: 'Manager — Tool stress replacement',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-replacement'],
    reaches: 'window',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-breakage' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-immune',
    label: 'Manager — Tool stress immune',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-immune'],
    reaches: 'window',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-breakage' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-parity-04-requirements-1280x720',
    label: 'Manager — Tool parity 04 requirements 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-04-requirements-1280x720'],
    reaches: 'exact',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-requirements' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-parity-05-validation-1280x720',
    label: 'Manager — Tool parity 05 validation 1280x720',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-05-validation-1280x720'],
    reaches: 'exact',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-validation' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 720 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-invalid-validation',
    label: 'Manager — Tool stress invalid validation',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-invalid-validation'],
    reaches: 'window',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-validation' },
    ],
    expectView: 'tool-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-parity-06-breakage-900x700',
    label: 'Manager — Tool parity 06 breakage 900x700',
    app: MANAGER,
    smokeLabels: ['manager-tool-parity-06-breakage-900x700'],
    reaches: 'exact',
    query: {},
    steps: [
      'Tools',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#tool-tab-breakage' },
    ],
    expectView: 'tool-edit',
    position: { width: 900, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'responsive', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ToolEditView\.svelte$/],
  },
  {
    id: 'manager-tool-stress-wrapping-680',
    label: 'Manager — Tool stress wrapping 680',
    app: MANAGER,
    smokeLabels: ['manager-tool-stress-wrapping-680'],
    reaches: 'exact',
    query: {},
    steps: ['Tools'],
    expectView: 'tools',
    position: { width: 680, height: 700 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'tools', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Tool/,
      /^src\/ui\/svelte\/apps\/manager\/tools\//,
    ],
  },
  {
    id: 'manager-knowledge-owned-copies',
    label: 'Manager — Knowledge owned copies',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-owned-copies'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/],
  },
  {
    id: 'manager-knowledge-empty-tab',
    label: 'Manager — Knowledge empty tab',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-empty-tab'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/],
  },
  {
    id: 'manager-knowledge-learned-lost-copy',
    label: 'Manager — Knowledge learned lost copy',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-learned-lost-copy'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/],
  },
  {
    id: 'manager-knowledge-party-pool-warning',
    label: 'Manager — Knowledge party pool warning',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-party-pool-warning'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/],
  },
  {
    id: 'manager-knowledge-delete-armed',
    label: 'Manager — Knowledge delete armed',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-delete-armed'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/],
  },
  {
    id: 'manager-knowledge-narrow',
    label: 'Manager — Knowledge narrow',
    app: MANAGER,
    smokeLabels: ['manager-knowledge-narrow'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-knowledge' }],
    expectView: 'knowledge',
    position: { width: 880, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'knowledge', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/KnowledgeView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/knowledge\//,
    ],
  },
  {
    id: 'manager-components-progressive',
    label: 'Manager — Components progressive',
    app: MANAGER,
    smokeLabels: ['manager-components-progressive'],
    reaches: 'exact',
    query: { system: 'lab-herbalism' },
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-components-bulk-edit-progressive',
    label: 'Manager — Components bulk edit progressive',
    app: MANAGER,
    smokeLabels: ['manager-components-bulk-edit-progressive'],
    reaches: 'window',
    query: { system: 'lab-herbalism' },
    steps: ['Components'],
    expectView: 'components',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/Component/,
      /^src\/ui\/svelte\/apps\/manager\/components?\//,
    ],
  },
  {
    id: 'manager-component-edit-difficulty',
    label: 'Manager — Component edit difficulty',
    app: MANAGER,
    smokeLabels: ['manager-component-edit-difficulty'],
    reaches: 'exact',
    query: {},
    steps: [
      'Components',
      {
        selector:
          '.manager-component-row[data-component-id="sm-ruby"] .manager-icon-button[aria-label^="Edit"]',
      },
    ],
    expectView: 'component-edit',
    position: { width: 1280, height: 900 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'components', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/ComponentEditView\.svelte$/],
  },
  {
    id: 'manager-import-report',
    label: 'Manager — Import report',
    app: MANAGER,
    smokeLabels: ['manager-import-report'],
    reaches: 'window',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
      /^src\/ui\/svelte\/apps\/manager\/Import(ReportModal|FolderMappingModal)\.svelte$/,
    ],
  },
  {
    id: 'manager-import-folder-mapping',
    label: 'Manager — Import folder mapping',
    app: MANAGER,
    smokeLabels: ['manager-import-folder-mapping'],
    reaches: 'window',
    query: {},
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'manager-alchemy-settings',
    label: 'Manager — Alchemy settings',
    app: MANAGER,
    smokeLabels: ['manager-alchemy-settings'],
    reaches: 'exact',
    query: { system: 'lab-alchemy' },
    steps: ['Crafting', { selector: '#manager-crafting-nav-settings' }],
    expectView: 'crafting-settings',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'crafting-settings'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/CraftingSettingsView\.svelte$/],
  },
  {
    id: 'manager-experimental-off',
    label: 'Manager — Experimental off',
    app: MANAGER,
    smokeLabels: ['manager-experimental-off'],
    reaches: 'exact',
    query: { experimental: '0' },
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/CraftingSystemManagerRoot\.svelte$/,
      /^src\/ui\/svelte\/stores\/adminStore\.js$/,
    ],
  },
  {
    id: 'player-gathering-environments',
    label: 'Player app — Gathering environments',
    app: PLAYER,
    smokeLabels: ['player-gathering-environments'],
    reaches: 'exact',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'fabricate-app-shell',
    label: 'Player app — App shell',
    app: PLAYER,
    smokeLabels: ['fabricate-app-shell'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
      /^src\/ui\/svelte\/apps\/FabricateAppRoot\.svelte$/,
    ],
  },
  {
    id: 'player-inventory',
    label: 'Player app — Inventory',
    app: PLAYER,
    smokeLabels: ['player-inventory'],
    reaches: 'exact',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-salvage',
    label: 'Player app — Salvage',
    app: PLAYER,
    smokeLabels: ['player-salvage'],
    reaches: 'window',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-salvage-no-check',
    label: 'Player app — Salvage no check',
    app: PLAYER,
    smokeLabels: ['player-salvage-no-check'],
    reaches: 'window',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-salvage-tools',
    label: 'Player app — Salvage tools',
    app: PLAYER,
    smokeLabels: ['player-salvage-tools'],
    reaches: 'window',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-inventory-multi-system',
    label: 'Player app — Inventory multi system',
    app: PLAYER,
    smokeLabels: ['player-inventory-multi-system'],
    reaches: 'exact',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-salvage-misconfigured',
    label: 'Player app — Salvage misconfigured',
    app: PLAYER,
    smokeLabels: ['player-salvage-misconfigured'],
    reaches: 'window',
    query: { tab: 'inventory' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'inventory', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/inventory\//,
      /^src\/ui\/svelte\/stores\/inventoryStore/,
    ],
  },
  {
    id: 'player-gathering-events',
    label: 'Player app — Gathering events',
    app: PLAYER,
    smokeLabels: ['player-gathering-events'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-task-ready',
    label: 'Player app — Gathering task ready',
    app: PLAYER,
    smokeLabels: ['player-gathering-task-ready'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-after-success',
    label: 'Player app — Gathering after success',
    app: PLAYER,
    smokeLabels: ['player-gathering-after-success'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-tool-blocked',
    label: 'Player app — Gathering tool blocked',
    app: PLAYER,
    smokeLabels: ['player-gathering-tool-blocked'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-timed-ready',
    label: 'Player app — Gathering timed ready',
    app: PLAYER,
    smokeLabels: ['player-gathering-timed-ready'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-timed-active',
    label: 'Player app — Gathering timed active',
    app: PLAYER,
    smokeLabels: ['player-gathering-timed-active'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-blind',
    label: 'Player app — Gathering blind',
    app: PLAYER,
    smokeLabels: ['player-gathering-blind'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-realm-locked',
    label: 'Player app — Gathering realm locked',
    app: PLAYER,
    smokeLabels: ['player-gathering-realm-locked'],
    reaches: 'window',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-gathering-stacked',
    label: 'Player app — Gathering stacked',
    app: PLAYER,
    smokeLabels: ['player-gathering-stacked'],
    reaches: 'exact',
    query: { tab: 'gathering' },
    steps: [],
    position: { width: 1024, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'gathering', 'responsive', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/gathering\//],
  },
  {
    id: 'player-crafting-simple',
    label: 'Player app — Crafting simple',
    app: PLAYER,
    smokeLabels: ['player-crafting-simple'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-ingredient-routed',
    label: 'Player app — Crafting ingredient routed',
    app: PLAYER,
    smokeLabels: ['player-crafting-ingredient-routed'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="jw-r-cast"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-routed-by-check',
    label: 'Player app — Crafting routed by check',
    app: PLAYER,
    smokeLabels: ['player-crafting-routed-by-check'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="rw-r-blade"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-run-summary',
    label: 'Player app — Crafting run summary',
    app: PLAYER,
    smokeLabels: ['player-crafting-run-summary'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-roll-result',
    label: 'Player app — Crafting roll result',
    app: PLAYER,
    smokeLabels: ['player-crafting-roll-result'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-alternative',
    label: 'Player app — Crafting essence alternative',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-alternative'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-emberbrand"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-alternatives',
    label: 'Player app — Crafting alternatives',
    app: PLAYER,
    smokeLabels: ['player-crafting-alternatives'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-longsword"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-legacy',
    label: 'Player app — Crafting essence legacy',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-legacy'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-ingredient',
    label: 'Player app — Crafting essence ingredient',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-ingredient'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-emberbrand"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-shopping',
    label: 'Player app — Crafting essence shopping',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-shopping'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-deepbind"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-slot-rail',
    label: 'Player app — Crafting slot rail',
    app: PLAYER,
    smokeLabels: ['player-crafting-slot-rail'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-pattern-blade"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-tag-unmatched',
    label: 'Player app — Crafting tag unmatched',
    app: PLAYER,
    smokeLabels: ['player-crafting-tag-unmatched'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-pool',
    label: 'Player app — Crafting essence pool',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-pool'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-deepbind"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-pick-for-me',
    label: 'Player app — Crafting pick for me',
    app: PLAYER,
    smokeLabels: ['player-crafting-pick-for-me'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-essence-pool-shared',
    label: 'Player app — Crafting essence pool shared',
    app: PLAYER,
    smokeLabels: ['player-crafting-essence-pool-shared'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-consumption-plan',
    label: 'Player app — Crafting consumption plan',
    app: PLAYER,
    smokeLabels: ['player-crafting-consumption-plan'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-shield"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-multistep',
    label: 'Player app — Crafting multistep',
    app: PLAYER,
    smokeLabels: ['player-crafting-multistep'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-pattern-blade"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-progressive',
    label: 'Player app — Crafting progressive',
    app: PLAYER,
    smokeLabels: ['player-crafting-progressive'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-progressive-reordered',
    label: 'Player app — Crafting progressive reordered',
    app: PLAYER,
    smokeLabels: ['player-crafting-progressive-reordered'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-progressive-fixed',
    label: 'Player app — Crafting progressive fixed',
    app: PLAYER,
    smokeLabels: ['player-crafting-progressive-fixed'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-progressive-stacked',
    label: 'Player app — Crafting progressive stacked',
    app: PLAYER,
    smokeLabels: ['player-crafting-progressive-stacked'],
    reaches: 'window',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1024, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-crafting-stacked',
    label: 'Player app — Crafting stacked',
    app: PLAYER,
    smokeLabels: ['player-crafting-stacked'],
    reaches: 'exact',
    query: { tab: 'crafting' },
    steps: [],
    position: { width: 1024, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'responsive', 'window-only'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/crafting\//,
      /^src\/ui\/svelte\/stores\/craftingStore/,
    ],
  },
  {
    id: 'player-alchemy-chooser',
    label: 'Player app — Alchemy chooser',
    app: PLAYER,
    smokeLabels: ['player-alchemy-chooser'],
    reaches: 'window',
    query: { tab: 'alchemy' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'alchemy', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/alchemy\//],
  },
  {
    id: 'player-alchemy-workbench',
    label: 'Player app — Alchemy workbench',
    app: PLAYER,
    smokeLabels: ['player-alchemy-workbench'],
    reaches: 'exact',
    query: { tab: 'alchemy' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'alchemy'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/alchemy\//],
  },
  {
    id: 'player-alchemy-stacked',
    label: 'Player app — Alchemy stacked',
    app: PLAYER,
    smokeLabels: ['player-alchemy-stacked'],
    reaches: 'exact',
    query: { tab: 'alchemy' },
    steps: [],
    position: { width: 1024, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'alchemy', 'responsive', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/alchemy\//],
  },
  {
    id: 'fabricate-journal',
    label: 'Player app — Journal',
    app: PLAYER,
    smokeLabels: ['fabricate-journal'],
    reaches: 'exact',
    query: { tab: 'journal' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'journal'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/journal\//, /^src\/ui\/svelte\/stores\/journalStore/],
  },
  {
    id: 'fabricate-journal-craft-detail',
    label: 'Player app — Journal craft detail',
    app: PLAYER,
    smokeLabels: ['fabricate-journal-craft-detail'],
    reaches: 'window',
    query: { tab: 'journal' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'journal', 'window-only'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/journal\//, /^src\/ui\/svelte\/stores\/journalStore/],
  },

  // ───────────────────────────────────────────────────────────────────────────────────────────────
  // Coverage matrix — states the live smoke does NOT photograph.
  //
  // Everything above mirrors a smoke frame, which makes the smoke the ceiling on coverage. It is
  // not a complete one: the smoke walks one system per screen, so whole rendering paths — the two
  // routed resolution modes, two of the three visibility modes, Foundry's light theme — never
  // appear in any frame it produces. These cases carry `reaches: 'beyond'` and no `smokeLabels`,
  // which is the registry's way of saying "no smoke counterpart exists to compare against".
  // ───────────────────────────────────────────────────────────────────────────────────────────────

  {
    id: 'coverage-mode-routed-ingredients-results',
    label: 'Coverage — routedByIngredients results',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-jewelry' },
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'resolution-mode'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
      /^src\/systems\/ResolutionModeService\.js$/,
    ],
  },
  {
    id: 'coverage-mode-routed-check-results',
    label: 'Coverage — routedByCheck results',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-runework' },
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-results' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'resolution-mode'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/recipe\//,
      /^src\/systems\/ResolutionModeService\.js$/,
    ],
  },
  {
    id: 'coverage-mode-routed-check-checks',
    label: 'Coverage — routedByCheck outcome tiers',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-runework' },
    steps: ['Checks', { selector: '#checks-tab-crafting' }],
    expectView: 'checks',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'checks', 'resolution-mode'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/checks\//],
  },

  // Player recipe detail, one per resolution mode. Each mode draws a DIFFERENT body — the routed
  // ones a route rail, progressive a stage rail, simple a plain ingredient list — so the four
  // frames together are the only side-by-side evidence that a change to one did not move another.
  {
    id: 'coverage-mode-simple-detail',
    label: 'Coverage — simple recipe detail',
    app: PLAYER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="sm-r-longsword"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'resolution-mode'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/crafting\//],
  },
  // KNOWN GAP — no `coverage-mode-progressive-detail`. The only progressive system in the fixture
  // is `lab-herbalism`, which is knowledge-gated on purpose (that is what makes the Books & Scrolls
  // and Knowledge rails exist at all), so a player who has learned nothing sees none of its recipes
  // and there is no row to click. Closing this properly means either granting the lab player
  // knowledge — which changes the recipe list in EVERY existing player frame — or adding a sixth,
  // progressive-and-global system. Both are larger than the frame is worth right now; the
  // progressive AUTHORING path is covered by `manager-recipe-edit-results-progressive`.
  {
    id: 'coverage-mode-routed-ingredients-detail',
    label: 'Coverage — routedByIngredients recipe detail',
    app: PLAYER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { tab: 'crafting' },
    // Brenna holds the silver billet and not the gold one, so this frame shows one route satisfied
    // and one short — which is the only way a routed body's routing is visible at all.
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="jw-r-cast"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'resolution-mode'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/crafting\//],
  },
  {
    id: 'coverage-mode-routed-check-detail',
    label: 'Coverage — routedByCheck recipe detail',
    app: PLAYER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { tab: 'crafting' },
    steps: [{ selector: '.crafting-recipe-row[data-recipe-id="rw-r-blade"]' }],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'resolution-mode'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/crafting\//],
  },

  // Visibility mode changes which rails EXIST, not merely what they contain — a restricted system
  // has an Access rail, a knowledge-gated one has Books & Scrolls and Knowledge, a global one has
  // neither. The smoke walks a single system, so two of the three were never photographed.
  {
    id: 'coverage-visibility-global',
    label: 'Coverage — global visibility system',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-smithing' },
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system', 'visibility-mode'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/system\//,
    ],
  },
  {
    id: 'coverage-visibility-knowledge',
    label: 'Coverage — knowledge-gated system',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-herbalism' },
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system', 'visibility-mode'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/system\//,
    ],
  },
  {
    id: 'coverage-visibility-restricted',
    label: 'Coverage — restricted system',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-alchemy' },
    steps: ['System Overview', { selector: '#system-tab-settings' }],
    expectView: 'system-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'system', 'visibility-mode'],
    sourceMatches: [
      /^src\/ui\/svelte\/apps\/manager\/SystemEditView\.svelte$/,
      /^src\/ui\/svelte\/apps\/manager\/system\//,
    ],
  },

  // Foundry's LIGHT application theme. Everything else in this registry renders `theme-dark`,
  // because that is what the smoke world is configured for — but a GM is free to run light, and
  // `styles/fabricate.css` sets no heading colour of its own, so headings inherit Foundry's
  // `--color-text-primary`: rgb(17,17,17) under light, on Fabricate's own dark panels. These two
  // frames are the evidence for that, and the regression guard once it is fixed.
  {
    id: 'coverage-theme-light-player',
    label: 'Coverage — player app on Foundry light theme',
    app: PLAYER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { tab: 'crafting', colorScheme: 'light' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'theme'],
    sourceMatches: [/^styles\/fabricate\.css$/, /^src\/ui\/theme\.js$/],
  },
  {
    id: 'coverage-theme-light-manager',
    label: 'Coverage — manager on Foundry light theme',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { colorScheme: 'light' },
    steps: [],
    expectView: 'systems',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'systems', 'theme'],
    sourceMatches: [/^styles\/fabricate\.css$/, /^src\/ui\/theme\.js$/],
  },

  // Feature toggles that remove UI. `multiStepRecipes: false` (the jewellers) drops the step rail
  // and the Multi-step chip from the recipe editor; `experimental: '0'` drops the Graph rail entry.
  // Both were only ever photographed in their ON state on the player side.
  {
    id: 'coverage-multistep-off-recipe-editor',
    label: 'Coverage — multi-step disabled recipe editor',
    app: MANAGER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { system: 'lab-jewelry' },
    steps: [
      'Crafting',
      { selector: '.manager-icon-button[aria-label^="Edit"]' },
      { selector: '#recipe-tab-overview' },
    ],
    expectView: 'recipe-edit',
    position: { width: 1280, height: 820 },
    readySelector: '.fabricate-manager',
    publish: true,
    kinds: ['manager', 'recipes', 'settings'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/manager\/recipe\//],
  },
  {
    id: 'coverage-experimental-off-player',
    label: 'Coverage — player app with experimental off',
    app: PLAYER,
    smokeLabels: [],
    reaches: 'beyond',
    query: { tab: 'crafting', experimental: '0' },
    steps: [],
    position: { width: 1280, height: 860 },
    readySelector: '.fabricate-app-shell',
    publish: true,
    kinds: ['player', 'crafting', 'settings'],
    sourceMatches: [/^src\/ui\/svelte\/apps\/crafting\//],
  },
]);

/**
 * Normalize a changed-file path to repository-relative POSIX form.
 *
 * @param {string} filePath Path from a diff.
 * @returns {string} Normalized path.
 */
export function normalizePath(filePath) {
  return String(filePath ?? '')
    .trim()
    .replaceAll('\\', '/')
    .replace(/^\.\//, '');
}

/**
 * Whether one path can change what a window looks like.
 *
 * @param {string} filePath Repository-relative path.
 * @returns {boolean} True for render-affecting paths.
 */
export function isUiFile(filePath) {
  return UI_PATH_PATTERN.test(normalizePath(filePath));
}

/**
 * Whether a changed set requires screenshot evidence at all. A `lang/`-only change does not — but a
 * `lang/` change alongside a render file does, which is why this tests the whole set.
 *
 * @param {string[]} files Changed paths.
 * @returns {boolean} True when evidence is required.
 */
export function hasUiChanges(files = []) {
  const normalized = files.map((file) => normalizePath(file));
  if (normalized.some((file) => isUiFile(file))) return true;
  return false;
}

export const caseIds = Object.freeze(VIEW_LAB_CASES.map((viewCase) => viewCase.id));

/**
 * @param {string} id Case id.
 * @returns {object|null} The case, or null.
 */
export function getCaseById(id) {
  return VIEW_LAB_CASES.find((viewCase) => viewCase.id === id) ?? null;
}

/**
 * Resolve a case's human-facing label. Wired into the S3 publish path so the PR body's alt text
 * comes from this registry rather than from the legacy `VIEW_RECIPES` table.
 *
 * @param {string} id Case id.
 * @returns {string|null} Label, or null when the id is unknown.
 */
export function labelForCaseId(id) {
  return getCaseById(id)?.label ?? null;
}

export function fallbackCase() {
  return getCaseById(FALLBACK_CASE_ID);
}

/**
 * Map a changed-file set onto the cases that should be captured.
 *
 * @param {string[]} files Changed paths.
 * @returns {object[]} Cases to capture, in registry order.
 */
export function mapChangedFilesToCases(files = []) {
  const normalized = files.map((file) => normalizePath(file)).filter(Boolean);

  // A change to the lab's own fixture world or to this registry selects EVERYTHING that publishes.
  //
  // This is the rule that stops the harness lying about its riskiest change. Every frame renders
  // from one fixture world, so an edit to `labContent.js` can reflow all 150 — and none of those
  // paths is a render file, so `isUiFile` rejects them and the selection came back EMPTY. The PRs
  // most able to invalidate the whole corpus were precisely the PRs that selected no evidence and
  // passed green. Verified before this rule existed:
  //   mapChangedFilesToCases(['tests/view-lab/world/labContent.js']) -> []
  if (normalized.some((file) => LAB_INFRASTRUCTURE_PATTERN.test(file))) {
    return publishableCases();
  }

  const renderFiles = normalized.filter((file) => isUiFile(file));
  if (renderFiles.length === 0) {
    // Nothing here renders, so there is no frame to select — a lang-only change included. The
    // MIXED case (a `lang/` edit shipping alongside render files) never reaches this branch at all,
    // because those render files put `renderFiles.length` above zero and selection proceeds below;
    // callers test `hasUiChanges` over the whole set for that distinction.
    //
    // This previously read `normalized.some(isLang) ? [] : []` — a ternary whose branches were
    // identical, guarding a distinction that had already been made two lines above. It selected
    // nothing either way, so it was dead, and the comment above it described a fallback return the
    // code did not perform.
    return [];
  }

  const selected = new Set();
  let sawBroadSignal = false;
  for (const file of renderFiles) {
    if (BROAD_SIGNAL_PATTERN.test(file)) {
      sawBroadSignal = true;
      continue;
    }
    for (const viewCase of VIEW_LAB_CASES) {
      if (viewCase.sourceMatches.some((pattern) => pattern.test(file))) selected.add(viewCase.id);
    }
  }

  if (sawBroadSignal) for (const id of REPRESENTATIVE_CASE_IDS) selected.add(id);
  if (selected.size === 0) selected.add(FALLBACK_CASE_ID);

  return VIEW_LAB_CASES.filter((viewCase) => selected.has(viewCase.id) && viewCase.publish);
}

/**
 * Every case that publishes, for a full capture run.
 *
 * @returns {object[]} Publishable cases.
 */
export function publishableCases() {
  return VIEW_LAB_CASES.filter((viewCase) => viewCase.publish);
}
