/** The counting pool's closure (issue 2006), for a suite mounting the Formula card on its own. */
export const COUNT_POOL_RAW_MODULES = Object.freeze([
  'src/ui/svelte/components/stepperLabels.js',
  'src/ui/svelte/util/iconPickerPopover.js',
  'src/ui/svelte/util/listboxNavigation.js',
  'src/ui/svelte/util/pickerOptionModel.js',
  'src/ui/svelte/util/overlayHost.js',
  'src/ui/svelte/util/overlayBounds.js',
  'src/ui/svelte/actions/dismissOnOutsideClick.js',
  'src/ui/svelte/actions/portal.js',
  'src/ui/svelte/actions/anchoredPopover.js',
  'src/systems/characterModifierPrerequisiteCopy.js',
  'src/systems/characterPrerequisites.js',
  'src/systems/checkEvaluation.js',
  'src/systems/checkTarget.js',
  'src/systems/countEvaluation.js',
  'src/utils/localizeWithFallback.js',
  'src/utils/scalars.js',
  'src/ui/svelte/apps/manager/checks/checkTargetStatus.js',
  'src/ui/svelte/apps/manager/checks/countInsetModel.js',
  'src/ui/svelte/apps/manager/checks/countPoolOptions.js',
]);

export const COUNT_POOL_COMPILED_MODULES = Object.freeze([
  'src/ui/svelte/components/EmptyState.svelte',
  'src/ui/svelte/components/Field.svelte',
  'src/ui/svelte/components/ManagerButton.svelte',
  'src/ui/svelte/components/Select.svelte',
  'src/ui/svelte/components/SearchablePopover.svelte',
  'src/ui/svelte/components/SearchablePopoverPanel.svelte',
  'src/ui/svelte/components/Stepper.svelte',
  'src/ui/svelte/apps/manager/RollDataExpressionInput.svelte',
  'src/ui/svelte/apps/manager/checks/CheckCharacterValueField.svelte',
  'src/ui/svelte/apps/manager/checks/CheckCountInputField.svelte',
  'src/ui/svelte/apps/manager/checks/CheckCountInset.svelte',
  'src/ui/svelte/apps/manager/checks/CheckCountPoolFields.svelte',
]);
